<?php

return [
  'it' => [
    'locale' => 'it_IT',
    'meta' => [
      'title' => 'Trackers Lens — AI per Dati Realtime',
      'description' => 'Monitora API, WebSocket, RSS e dati realtime nel browser. Crea dashboard, tracker AI e automazioni locali privacy-first.',
    ],
    'accessibility' => ['skip' => 'Salta al contenuto', 'language' => 'Lingua'],
    'nav' => [
      'features' => 'Funzionalita',
      'why' => 'Perche Trackers Lens',
      'marketplace' => 'Marketplace',
      'pricing' => 'Prezzi',
      'docs' => 'Documentazione',
      'login' => 'Accedi',
      'download' => 'Avvisami',
    ],
    'hero' => [
      'badge' => 'AI-powered • Privacy first • Open ecosystem',
      'title' => 'Il tuo centro di controllo per i dati',
      'subtitle' => 'Monitora qualsiasi fonte di dati, in locale o da API pubbliche. Costruisci dashboard intelligenti, automatizza analisi e prendi decisioni basate su insight reali.',
      'ctaPrimary' => 'Avvisami al Lancio',
      'ctaSecondary' => 'Guarda la Demo',
      'devLabel' => 'In sviluppo attivo',
      'devStatus' => 'Plugin browser in preparazione',
      'devBody' => 'Stiamo finalizzando runtime locale, marketplace e pacchetto plugin. Il download sara disponibile presto.',
      'devProgress' => 'Progress release',
      'trustPrivate' => '100% privato',
      'trustLocal' => 'Dati sempre locali',
      'trustOpen' => 'Open Source',
      'metricTrackers' => 'Tracker attivi',
      'metricData' => 'Dati processati',
      'metricInsights' => 'AI Insights',
      'metricActions' => 'Azioni automatiche',
      'chartActivity' => 'Attivita realtime',
      'chartResources' => 'Utilizzo risorse',
    ],
    'value' => [
      'title' => 'Potenza. Flessibilita. Intelligenza.',
      'subtitle' => 'Tutto in un unico ecosistema.',
      'cards' => [
        'monitor' => ['title' => 'Monitora tutto', 'body' => 'Dati da API, WebSocket, RSS, database, file e molto altro. Tutto in tempo reale.'],
        'ai' => ['title' => 'AI Integrata', 'body' => 'Analisi intelligenti, sintesi automatiche e alert predittivi alimentati dall\'AI.'],
        'automation' => ['title' => 'Automazioni', 'body' => 'Crea regole, trigger e azioni automatiche basate sui tuoi dati e condizioni.'],
        'visual' => ['title' => 'Visualizzazioni', 'body' => 'Dashboard personalizzabili per ogni esigenza. Da semplici a avanzate.'],
        'privacy' => ['title' => 'Privacy First', 'body' => 'Esecuzione locale, dati sul tuo dispositivo e nessun cloud obbligatorio.'],
        'open' => ['title' => 'Ecosistema Aperto', 'body' => 'Plugin, marketplace e componenti estendibili per costruire il tuo workflow.'],
      ],
    ],
    'privacy' => [
      'badge' => 'Privacy First',
      'title' => 'I tuoi dati, il tuo controllo.',
      'body' => 'Nessun cloud obbligatorio. Trackers Lens esegue i tuoi asset nel plugin browser, usa IndexedDB locale e chiama API direttamente dal dispositivo utente. Nessun server centrale deve eseguire i tuoi asset.',
      'pointCloud' => ['title' => 'Nessun cloud obbligatorio', 'body' => 'Sincronizzi solo quando vuoi.'],
      'pointRuntime' => ['title' => 'Runtime locale', 'body' => 'Esecuzione nel plugin browser.'],
      'pointDb' => ['title' => 'IndexedDB locale', 'body' => 'Persistenza dati sul dispositivo.'],
      'pointApi' => ['title' => 'API dal tuo device', 'body' => 'Richieste originate dal client utente.'],
    ],
    'architecture' => [
      'title' => 'Tre pilastri. Un ecosistema.',
      'site' => ['title' => 'Sito web / marketplace', 'body' => 'Scopri, installa e condividi box, tracker, lens e modelli pronti per il tuo flusso di lavoro.'],
      'plugin' => ['title' => 'Plugin browser runtime locale', 'body' => 'Un ambiente operativo nel browser per eseguire tracker, dashboard e automazioni vicino ai dati.'],
      'chromium' => ['title' => 'Futuro ambiente dedicato Chromium fork', 'body' => 'Una base dedicata per runtime avanzati, isolamento, performance e tooling professionale.'],
    ],
    'boxes' => [
      'title' => 'Costruisci con boxLens e boxTracker',
      'body' => 'boxLens gestisce visualizzazione HTML, CSS e UI. boxTracker orchestra dati, API, WebSocket, RSS, AI e automazioni. Tracker e lens comunicano tramite canali dati chiari e componibili.',
    ],
    'developers' => [
      'title' => 'Sviluppa. Estendi. Personalizza.',
      'body' => 'Trackers Lens e open source e pensato per gli sviluppatori. Crea i tuoi box, integra le tue API e contribuisci all\'ecosistema.',
      'docs' => 'Documentazione',
      'api' => 'API Reference',
      'examples' => 'Esempi',
      'community' => 'Community',
    ],
    'stats' => ['users' => 'utenti attivi', 'trackers' => 'tracker creati', 'data' => 'dati elaborati', 'uptime' => 'uptime locale'],
    'pricing' => [
      'title' => 'Prezzi semplici per partire subito.',
      'subtitle' => 'Inizia con il plugin gratuito e scala quando il tuo ecosistema cresce.',
      'free' => ['label' => 'Free', 'price' => 'Gratis', 'body' => 'Runtime locale, tracker personali, dashboard e marketplace pubblico.'],
      'pro' => ['label' => 'Pro', 'price' => 'Presto', 'body' => 'Workspace avanzati, automazioni potenziate e strumenti per team professionali.'],
      'enterprise' => ['label' => 'Enterprise', 'price' => 'Custom', 'body' => 'Distribuzioni dedicate, policy di sicurezza e supporto per ambienti regolati.'],
    ],
    'cta' => [
      'title' => 'In sviluppo ora. Lancio in arrivo.',
      'download' => 'Avvisami al Lancio',
      'demo' => 'Guarda la Demo',
      'note' => 'Il plugin sara scaricabile presto. Nessuna registrazione richiesta per seguire il lancio.',
    ],
    'footer' => [
      'brandText' => 'Il centro di controllo AI-powered per monitorare, analizzare e automatizzare qualsiasi fonte di dati.',
      'product' => 'Prodotto',
      'features' => 'Funzionalita',
      'pricing' => 'Pricing',
      'roadmap' => 'Roadmap',
      'changelog' => 'Changelog',
      'resources' => 'Risorse',
      'docs' => 'Documentazione',
      'api' => 'API Reference',
      'examples' => 'Esempi',
      'blog' => 'Blog',
      'company' => 'Azienda',
      'about' => 'Chi siamo',
      'contact' => 'Contatti',
      'privacy' => 'Privacy Policy',
      'terms' => 'Termini di servizio',
      'newsletter' => 'Newsletter',
      'newsletterText' => 'Iscriviti alla newsletter per novita, aggiornamenti e guide.',
      'emailPlaceholder' => 'La tua email',
      'newsletterSubmit' => 'Iscriviti',
      'copyright' => '© 2026 Trackers Lens. Tutti i diritti riservati.',
    ],
    'auth' => [
      'close' => 'Chiudi login',
      'kicker' => 'Accesso dashboard',
      'loginTitle' => 'Accedi a Trackers Lens',
      'loginBody' => 'Usa il tuo account per entrare nella dashboard cloud e gestire asset, box e workspace.',
      'tabsLabel' => 'Modalita accesso',
      'loginTab' => 'Login',
      'registerTab' => 'Crea account',
      'name' => 'Nome',
      'email' => 'Email',
      'password' => 'Password',
      'passwordConfirmation' => 'Conferma password',
      'remember' => 'Ricordami',
      'loginSubmit' => 'Accedi',
      'registerSubmit' => 'Crea account',
      'connecting' => 'Connessione all\'API...',
      'failed' => 'Accesso non riuscito. Controlla i dati e riprova.',
      'success' => 'Accesso riuscito. Apertura dashboard...',
      'saving' => 'Salvataggio...',
      'newsletterSaved' => 'Email salvata. Ti avviseremo al lancio.',
    ],
    'launch' => [
      'close' => 'Chiudi avviso lancio',
      'kicker' => 'Lancio in arrivo',
      'title' => 'Lascia la tua email',
      'body' => 'Ti avviseremo quando il plugin Trackers Lens sara pronto per il download e quando apriremo i primi accessi.',
      'submit' => 'Avvisami al lancio',
      'note' => 'Niente spam. Solo aggiornamenti importanti su release, plugin e accesso anticipato.',
      'invalid' => 'Inserisci una email valida.',
    ],
    'contact' => [
      'close' => 'Chiudi contatti',
      'kicker' => 'Contatti',
      'title' => 'Parliamo di Trackers Lens',
      'body' => 'Scrivici per accesso anticipato, partnership, supporto o domande tecniche sul runtime.',
      'message' => 'Messaggio',
      'submit' => 'Invia messaggio',
      'note' => 'Il messaggio viene salvato in modo sicuro e inviato al team Trackers Lens.',
      'success' => 'Messaggio inviato. Ti risponderemo presto.',
      'invalid' => 'Compila tutti i campi richiesti.',
    ],
    'pages' => [
      'about' => [
        'metaTitle' => 'Chi siamo — Trackers Lens',
        'metaDescription' => 'Chi siamo Trackers Lens: manifesto, principi e visione per un runtime locale AI-powered, leggibile e controllabile.',
        'badge' => 'Chi siamo',
        'title' => 'Dati quotidiani trasformati in un runtime controllabile.',
        'lead' => 'Trackers Lens nasce da una scelta semplice e impegnativa: costruire strumenti che restano leggibili, locali e onesti mentre il progetto cresce.',
        'note' => 'Non e solo una dashboard. E un modo di lavorare: meno rumore, piu controllo, piu cura per il dettaglio. Ogni tracker, lens e workspace deve ridurre la distanza tra dato, decisione e interfaccia reale.',
        'manifestoBadge' => 'Manifesto',
        'manifestoTitle' => 'Il manifesto dietro Trackers Lens',
        'principles' => [
          'p1' => ['title' => 'Controllo', 'body' => 'L utente deve vedere dove vivono i dati, quali tracker girano e cosa viene sincronizzato.'],
          'p2' => ['title' => 'Local-first', 'body' => 'Il runtime parte dal browser e da IndexedDB: cloud solo quando serve davvero.'],
          'p3' => ['title' => 'Componibilita', 'body' => 'boxLens, boxTracker e workspace devono unirsi senza diventare una struttura rigida.'],
          'p4' => ['title' => 'Precisione', 'body' => 'Ogni pannello deve spiegare cosa misura, da dove arriva e quando e stato aggiornato.'],
          'p5' => ['title' => 'Privacy', 'body' => 'Permessi, API keys e automazioni devono restare espliciti e governabili.'],
          'p6' => ['title' => 'Resilienza', 'body' => 'Tracker, retry, log e monitor devono rendere leggibili errori e stati runtime.'],
          'p7' => ['title' => 'Semplicita', 'body' => 'Aggiungere potenza senza aggiungere confusione: meno layer, piu intenzione.'],
          'p8' => ['title' => 'Evoluzione', 'body' => 'Plugin oggi, dashboard cloud domani, app dedicata quando il runtime sara maturo.'],
          'p9' => ['title' => 'Apertura', 'body' => 'Asset, template e marketplace devono favorire riuso, studio e collaborazione.'],
          'p10' => ['title' => 'Disciplina', 'body' => 'Qualita quotidiana: documentare, testare, limare e rendere il prodotto piu chiaro.'],
        ],
        'storyBadge' => 'Carlos Malleux',
        'story' => [
          'one' => 'Trackers Lens non e partito come un altra app generica. E partito come un bisogno: controllare fonti dati, automazioni e interfacce senza perdere chiarezza.',
          'two' => 'Nel tempo e cresciuto togliendo ambiguita: boxLens per visualizzare, boxTracker per raccogliere, workspace per comporre, IndexedDB per tenere il runtime vicino al dispositivo.',
          'three' => 'L obiettivo non e creare una scatola chiusa, ma rendere i dati piu usabili, diretti e verificabili, con AI e automazioni al servizio dell utente.',
          'four' => 'Trackers Lens e il risultato di questo processo: un ecosistema locale-first pensato per diventare un app professionale senza rinunciare al controllo.',
          'footer' => 'Trackers Lens e costruito con questa energia: lavoro tecnico paziente, cura per il dettaglio e qualita come direzione quotidiana.',
        ],
      ],
      'features' => [
        'metaTitle' => 'Funzionalita Plugin — Trackers Lens',
        'metaDescription' => 'Funzionalita del plugin Trackers Lens: runtime locale, workspace, boxLens, boxTracker, AI, IndexedDB e monitoraggio realtime.',
        'badge' => 'Plugin oggi • App runtime domani',
        'title' => 'Funzionalita del plugin Trackers Lens',
        'subtitle' => 'Il plugin e il primo runtime operativo: crea asset, compone workspace, esegue tracker, visualizza lens e tiene tutto vicino al browser. Nel tempo questa base evolvera in una vera app dedicata.',
        'cards' => [
          'plugin' => ['title' => 'Runtime locale nel browser', 'body' => 'Esecuzione locale, IndexedDB, asset salvati sul dispositivo e nessun cloud obbligatorio per lavorare.'],
          'workspace' => ['title' => 'Workspace componibili', 'body' => 'Griglie operative dove inserire boxLens, collegare sorgenti e costruire dashboard personali.'],
          'lens' => ['title' => 'boxLens visuali', 'body' => 'Componenti HTML, CSS e JS per trasformare dati in pannelli, grafici, widget e viste interattive.'],
          'tracker' => ['title' => 'boxTracker dati', 'body' => 'Processi per REST, RSS, WebSocket e manual data che producono canali verso i boxLens.'],
          'database' => ['title' => 'Explorer IndexedDB', 'body' => 'Libreria locale, workspace, collegamenti, impostazioni e cache ispezionabili dal prodotto.'],
          'ai' => ['title' => 'AI Runtime Center', 'body' => 'Centro prototipale per agenti, provider, prompt flow, memoria e jobs AI futuri.'],
        ],
        'futureTitle' => 'Dal plugin a una app completa.',
        'futureBody' => 'La direzione e chiara: partire dal plugin browser per validare runtime, box e workspace; collegare dashboard cloud e marketplace; poi consolidare il motore in una app dedicata con isolamento, worker, sincronizzazione e strumenti professionali.',
      ],
      'pricing' => [
        'metaTitle' => 'Pricing — Trackers Lens',
        'metaDescription' => 'Pricing Trackers Lens in working progress: plugin gratuito, piano Pro in arrivo e soluzioni Enterprise su richiesta.',
        'badge' => 'Working progress',
        'title' => 'Pricing in costruzione, senza sorprese.',
        'subtitle' => 'Il prodotto e ancora in sviluppo. Il plugin locale partira gratuito; i piani Pro e Enterprise arriveranno quando dashboard, marketplace e sincronizzazione saranno pronti.',
        'progressLabel' => 'Modello commerciale in definizione',
        'progressStatus' => 'Accesso gratuito al lancio',
        'progressBody' => 'Stiamo definendo limiti, workspace, AI usage, marketplace e supporto. Prima viene il prodotto stabile, poi il prezzo.',
        'freeBody' => 'Plugin locale, libreria, workspace personali, boxLens, boxTracker e runtime privacy-first.',
        'proBody' => 'Sincronizzazione cloud, workspace avanzati, automazioni, marketplace privato e strumenti per power user.',
        'enterpriseBody' => 'Distribuzioni dedicate, policy sicurezza, supporto, audit, ambienti regolati e integrazioni personalizzate.',
        'contact' => 'Contattaci',
      ],
      'roadmap' => [
        'metaTitle' => 'Roadmap — Trackers Lens',
        'metaDescription' => 'Roadmap Trackers Lens: plugin browser, dashboard cloud, marketplace, AI runtime e futura app dedicata.',
        'badge' => 'Roadmap prodotto',
        'title' => 'Roadmap pragmatica verso il runtime completo.',
        'subtitle' => 'La sequenza privilegia quello che rende il prodotto usabile: prima runtime locale e asset, poi account cloud, marketplace, AI e app dedicata.',
        'q2' => ['title' => 'Plugin locale e landing pubblica', 'body' => 'Stabilizzare library, editor workspace, boxLens, boxTracker, monitor runtime, documentazione API e flusso login.'],
        'q3' => ['title' => 'Dashboard cloud e account', 'body' => 'Collegare app.trackerslens.com all API reale: auth, profilo, asset cloud, API keys, statistiche e impostazioni.'],
        'q4' => ['title' => 'Marketplace e automazioni', 'body' => 'Pubblicazione box, template, versioning, installazione asset, changelog dei pacchetti e automazioni condivisibili.'],
        'y2027' => ['title' => 'App runtime dedicata', 'body' => 'Consolidare il motore oltre il plugin: worker persistenti, isolamento, sync controllata, AI jobs e strumenti professionali.'],
      ],
      'changelog' => [
        'metaTitle' => 'Changelog — Trackers Lens',
        'metaDescription' => 'Changelog Trackers Lens con avanzamenti su landing, API, dashboard, plugin runtime, workspace, editor, analytics e AI.',
        'badge' => 'Registro sviluppo',
        'title' => 'Changelog del prodotto.',
        'subtitle' => 'Un registro sintetico delle parti gia create o stabilizzate durante lo sviluppo di Trackers Lens.',
        'items' => [
          'site' => ['title' => 'Landing collegata ad API e dashboard', 'body' => 'Attivati link principali, popup login/register, newsletter locale, documentazione API pubblica e pagine prodotto.'],
          'dashboard' => ['title' => 'Dashboard cloud mockup operativo', 'body' => 'Creata dashboard command-center con KPI, activity, system status, quick actions e base per dati reali.'],
          'runtime' => ['title' => 'Runtime plugin e monitor boxTracker', 'body' => 'Workspace, viewer, monitor live, log eventi, pausa/play tracker, IndexedDB explorer, connections e analytics.'],
          'editors' => ['title' => 'Editor boxLens e boxTracker', 'body' => 'Editor stateful con salvataggio IndexedDB, edit mode da URL, CodeMirror, preview, metadata, parametri e test tracker.'],
        ],
      ],
      'docs' => [
        'metaTitle' => 'Documentazione — Trackers Lens',
        'metaDescription' => 'Documentazione Trackers Lens per plugin, runtime locale, workspace, boxLens, boxTracker, IndexedDB, monitor e API.',
        'badge' => 'Documentazione prodotto',
        'title' => 'Documentazione Trackers Lens',
        'subtitle' => 'Una guida pratica al plugin e al runtime locale costruita dalla documentazione reale in /Users/cmalleux/Sites/trackerLens.',
        'runtime' => ['title' => 'Runtime locale', 'body' => 'Trackers Lens nasce come plugin browser con esecuzione locale. Le pagine operative usano una sidebar comune e salvano asset, workspace e configurazioni in IndexedDB, lasciando i dati sul dispositivo quando non serve sincronizzare.'],
        'workspace' => ['title' => 'Workspace', 'body' => 'Il workspace e una griglia operativa. Salva solo riferimenti leggeri ai box sorgente, cosi se un boxLens viene aggiornato ogni workspace puo ricaricare la versione nuova dalla libreria.'],
        'boxes' => ['title' => 'boxLens e boxTracker', 'body' => 'boxLens gestisce visualizzazione HTML, CSS e JS. boxTracker e la parte dati: REST, RSS, WebSocket, trasformazioni, output channel, log, retry e stato runtime. I due comunicano tramite collegamenti e canali dati.'],
        'storage' => ['title' => 'IndexedDB e libreria locale', 'body' => 'Il database locale si chiama TrackersLens. Gli store principali sono tl_widgets per boxLens/boxTracker, tl_pages per workspace, tl_connections per collegamenti e tl_settings per preferenze.'],
        'screens' => ['title' => 'Schermate operative', 'body' => 'Oggi esistono library, editorWorkspace, workspace viewer, editorBoxLens, editorBoxTracker, database explorer, connections, analytics, AI Runtime Center e profilo. Alcune sono operative, altre sono mockup avanzati in preparazione.'],
        'api' => ['title' => 'API e dashboard cloud', 'body' => 'L API Laravel gestisce autenticazione, sessioni e dati persistenti. La dashboard app.trackerslens.com consumera gli endpoint /api/... mentre il plugin resta orientato al runtime locale.'],
      ],
      'privacy' => [
        'metaTitle' => 'Privacy Policy — Trackers Lens',
        'metaDescription' => 'Privacy Policy Trackers Lens: runtime locale, dati nel browser, API, account e comunicazioni.',
        'badge' => 'Privacy',
        'title' => 'Privacy Policy',
        'subtitle' => 'Trackers Lens e progettato privacy-first: il runtime locale viene prima del cloud obbligatorio.',
        'sections' => [
          's1' => ['title' => 'Dati locali', 'body' => 'Il plugin salva asset, workspace, collegamenti e impostazioni in IndexedDB sul dispositivo. Questi dati restano locali finche non abiliti funzionalita cloud o sincronizzazione.'],
          's2' => ['title' => 'Account e API', 'body' => 'Quando usi login, dashboard o servizi cloud, l API puo trattare email, sessione, profilo e dati necessari a fornire il servizio.'],
          's3' => ['title' => 'Newsletter e contatti', 'body' => 'I form pubblici servono per avvisarti del lancio o rispondere a richieste. Fino all endpoint dedicato, alcuni dati sono gestiti localmente o tramite email.'],
          's4' => ['title' => 'Controllo utente', 'body' => 'L obiettivo e rendere chiaro cosa resta locale, cosa viene sincronizzato e quali permessi usa ogni tracker o integrazione.'],
        ],
      ],
      'terms' => [
        'metaTitle' => 'Termini di servizio — Trackers Lens',
        'metaDescription' => 'Termini di servizio Trackers Lens per uso del plugin, dashboard, API, marketplace e contenuti.',
        'badge' => 'Termini',
        'title' => 'Termini di servizio',
        'subtitle' => 'Questa versione e una base operativa mentre il prodotto e in sviluppo attivo.',
        'sections' => [
          's1' => ['title' => 'Stato del prodotto', 'body' => 'Trackers Lens e in sviluppo. Funzionalita, prezzi, limiti, marketplace e dashboard possono cambiare durante la fase di lancio.'],
          's2' => ['title' => 'Uso responsabile', 'body' => 'L utente e responsabile delle sorgenti dati, API keys, endpoint e automazioni configurate nei propri tracker.'],
          's3' => ['title' => 'Asset e contenuti', 'body' => 'Box, workspace e template creati dall utente restano suoi. La pubblicazione futura nel marketplace richiedera regole specifiche di distribuzione.'],
          's4' => ['title' => 'Servizi cloud', 'body' => 'Dashboard, sincronizzazione e funzioni Pro/Enterprise saranno soggette a disponibilita, policy di sicurezza e condizioni dedicate.'],
        ],
      ],
      'blog' => [
        'metaTitle' => 'Blog — Trackers Lens',
        'metaDescription' => 'Blog Trackers Lens con note sviluppo su plugin, API, dashboard, runtime locale e AI.',
        'badge' => 'Blog',
        'title' => 'Note di sviluppo e prodotto',
        'subtitle' => 'Aggiornamenti sintetici su cosa stiamo costruendo e sulle scelte architetturali del runtime.',
        'items' => [
          'docs' => ['title' => 'Documentazione plugin pubblica', 'body' => 'Abbiamo trasformato il lavoro interno del plugin in una prima documentazione leggibile per runtime, workspace e box.'],
          'api' => ['title' => 'API contract leggibile', 'body' => 'La reference Laravel ora e una pagina HTML chiara, con raw Markdown disponibile per uso tecnico.'],
          'runtime' => ['title' => 'Dal plugin alla futura app', 'body' => 'Il runtime locale valida boxLens, boxTracker, IndexedDB e monitor prima di evolvere in una app dedicata.'],
        ],
      ],
    ],
  ],
  'en' => [
    'locale' => 'en_US',
    'meta' => [
      'title' => 'Trackers Lens — Local AI Data Monitoring',
      'description' => 'Monitor APIs, WebSocket, RSS and realtime data in your browser. Build AI dashboards, smart trackers and local automation.',
    ],
    'accessibility' => ['skip' => 'Skip to content', 'language' => 'Language'],
    'nav' => [
      'features' => 'Features',
      'why' => 'Why Trackers Lens',
      'marketplace' => 'Marketplace',
      'pricing' => 'Pricing',
      'docs' => 'Docs',
      'login' => 'Login',
      'download' => 'Notify Me',
    ],
    'hero' => [
      'badge' => 'AI-powered • Privacy first • Open ecosystem',
      'title' => 'Your data control center',
      'subtitle' => 'Monitor any data source locally or from public APIs. Build intelligent dashboards, automate analysis and make decisions based on real insights.',
      'ctaPrimary' => 'Notify Me at Launch',
      'ctaSecondary' => 'Watch Demo',
      'devLabel' => 'In active development',
      'devStatus' => 'Browser plugin in preparation',
      'devBody' => 'We are finalizing the local runtime, marketplace and plugin package. Download access is coming soon.',
      'devProgress' => 'Release progress',
      'trustPrivate' => '100% private',
      'trustLocal' => 'Always local data',
      'trustOpen' => 'Open Source',
      'metricTrackers' => 'Active trackers',
      'metricData' => 'Processed data',
      'metricInsights' => 'AI Insights',
      'metricActions' => 'Automated actions',
      'chartActivity' => 'Realtime activity',
      'chartResources' => 'Resource usage',
    ],
    'value' => [
      'title' => 'Power. Flexibility. Intelligence.',
      'subtitle' => 'Everything in one ecosystem.',
      'cards' => [
        'monitor' => ['title' => 'Monitor everything', 'body' => 'Data from APIs, WebSocket, RSS, databases, files and more. All in real time.'],
        'ai' => ['title' => 'Integrated AI', 'body' => 'Smart analysis, automatic summaries and predictive alerts powered by AI.'],
        'automation' => ['title' => 'Automations', 'body' => 'Create rules, triggers and automatic actions based on your data and conditions.'],
        'visual' => ['title' => 'Visualizations', 'body' => 'Custom dashboards for every need, from simple views to advanced interfaces.'],
        'privacy' => ['title' => 'Privacy First', 'body' => 'Local execution, data on your device and no mandatory cloud.'],
        'open' => ['title' => 'Open Ecosystem', 'body' => 'Plugins, marketplace and extensible components for building your workflow.'],
      ],
    ],
    'privacy' => [
      'badge' => 'Privacy First',
      'title' => 'Your data, your control.',
      'body' => 'No mandatory cloud. Trackers Lens runs your assets inside the browser plugin, uses local IndexedDB and calls APIs directly from the user\'s device. No central server has to execute your assets.',
      'pointCloud' => ['title' => 'No mandatory cloud', 'body' => 'Sync only when you choose.'],
      'pointRuntime' => ['title' => 'Local runtime', 'body' => 'Execution inside the browser plugin.'],
      'pointDb' => ['title' => 'Local IndexedDB', 'body' => 'Data persistence on the device.'],
      'pointApi' => ['title' => 'APIs from your device', 'body' => 'Requests originate from the user client.'],
    ],
    'architecture' => [
      'title' => 'Three pillars. One ecosystem.',
      'site' => ['title' => 'Website / marketplace', 'body' => 'Discover, install and share boxes, trackers, lenses and templates ready for your workflow.'],
      'plugin' => ['title' => 'Local browser plugin runtime', 'body' => 'An operating environment in the browser to run trackers, dashboards and automations near the data.'],
      'chromium' => ['title' => 'Future dedicated Chromium fork', 'body' => 'A dedicated base for advanced runtimes, isolation, performance and professional tooling.'],
    ],
    'boxes' => [
      'title' => 'Build with boxLens and boxTracker',
      'body' => 'boxLens handles HTML, CSS and UI visualization. boxTracker orchestrates data, APIs, WebSocket, RSS, AI and automations. Trackers and lenses communicate through clear, composable data channels.',
    ],
    'developers' => [
      'title' => 'Develop. Extend. Customize.',
      'body' => 'Trackers Lens is open source and built for developers. Create your own boxes, integrate your APIs and contribute to the ecosystem.',
      'docs' => 'Documentation',
      'api' => 'API Reference',
      'examples' => 'Examples',
      'community' => 'Community',
    ],
    'stats' => ['users' => 'active users', 'trackers' => 'trackers created', 'data' => 'data points processed', 'uptime' => 'local uptime'],
    'pricing' => [
      'title' => 'Simple pricing to start now.',
      'subtitle' => 'Start with the free plugin and scale when your ecosystem grows.',
      'free' => ['label' => 'Free', 'price' => 'Free', 'body' => 'Local runtime, personal trackers, dashboards and public marketplace.'],
      'pro' => ['label' => 'Pro', 'price' => 'Soon', 'body' => 'Advanced workspaces, stronger automations and tools for professional teams.'],
      'enterprise' => ['label' => 'Enterprise', 'price' => 'Custom', 'body' => 'Dedicated deployments, security policies and support for regulated environments.'],
    ],
    'cta' => [
      'title' => 'In development now. Launch coming soon.',
      'download' => 'Notify Me at Launch',
      'demo' => 'Watch Demo',
      'note' => 'The plugin will be available soon. No registration required to follow the launch.',
    ],
    'footer' => [
      'brandText' => 'The AI-powered control center to monitor, analyze and automate any data source.',
      'product' => 'Product',
      'features' => 'Features',
      'pricing' => 'Pricing',
      'roadmap' => 'Roadmap',
      'changelog' => 'Changelog',
      'resources' => 'Resources',
      'docs' => 'Documentation',
      'api' => 'API Reference',
      'examples' => 'Examples',
      'blog' => 'Blog',
      'company' => 'Company',
      'about' => 'About',
      'contact' => 'Contact',
      'privacy' => 'Privacy Policy',
      'terms' => 'Terms of Service',
      'newsletter' => 'Newsletter',
      'newsletterText' => 'Subscribe for news, updates and guides.',
      'emailPlaceholder' => 'Your email',
      'newsletterSubmit' => 'Subscribe',
      'copyright' => '© 2026 Trackers Lens. All rights reserved.',
    ],
    'auth' => [
      'close' => 'Close login',
      'kicker' => 'Dashboard access',
      'loginTitle' => 'Log in to Trackers Lens',
      'loginBody' => 'Use your account to enter the cloud dashboard and manage assets, boxes and workspaces.',
      'tabsLabel' => 'Auth mode',
      'loginTab' => 'Login',
      'registerTab' => 'Create account',
      'name' => 'Name',
      'email' => 'Email',
      'password' => 'Password',
      'passwordConfirmation' => 'Confirm password',
      'remember' => 'Remember me',
      'loginSubmit' => 'Login',
      'registerSubmit' => 'Create account',
      'connecting' => 'Connecting to the API...',
      'failed' => 'Login failed. Check your details and try again.',
      'success' => 'Login successful. Opening dashboard...',
      'saving' => 'Saving...',
      'newsletterSaved' => 'Email saved. We will notify you at launch.',
    ],
    'launch' => [
      'close' => 'Close launch notice',
      'kicker' => 'Launch coming soon',
      'title' => 'Leave your email',
      'body' => 'We will notify you when the Trackers Lens plugin is ready to download and when early access opens.',
      'submit' => 'Notify me at launch',
      'note' => 'No spam. Only important updates about releases, the plugin and early access.',
      'invalid' => 'Enter a valid email.',
    ],
    'contact' => [
      'close' => 'Close contact',
      'kicker' => 'Contact',
      'title' => 'Let us talk about Trackers Lens',
      'body' => 'Write for early access, partnerships, support or technical questions about the runtime.',
      'message' => 'Message',
      'submit' => 'Send message',
      'note' => 'The message is saved securely and sent to the Trackers Lens team.',
      'success' => 'Message sent. We will reply soon.',
      'invalid' => 'Fill in all required fields.',
    ],
    'pages' => [
      'about' => [
        'metaTitle' => 'About — Trackers Lens',
        'metaDescription' => 'About Trackers Lens: manifesto, principles and vision for a readable, controllable AI-powered local runtime.',
        'badge' => 'About',
        'title' => 'Daily data transformed into a controllable runtime.',
        'lead' => 'Trackers Lens comes from a simple and demanding choice: build tools that stay readable, local and honest as the project grows.',
        'note' => 'It is not only a dashboard. It is a way of working: less noise, more control, more care for detail. Every tracker, lens and workspace should shorten the distance between data, decision and real interface.',
        'manifestoBadge' => 'Manifesto',
        'manifestoTitle' => 'The manifesto behind Trackers Lens',
        'principles' => [
          'p1' => ['title' => 'Control', 'body' => 'Users should see where data lives, which trackers run and what gets synchronized.'],
          'p2' => ['title' => 'Local-first', 'body' => 'The runtime starts in the browser and IndexedDB: cloud only when it is truly needed.'],
          'p3' => ['title' => 'Composability', 'body' => 'boxLens, boxTracker and workspaces should connect without becoming a rigid structure.'],
          'p4' => ['title' => 'Precision', 'body' => 'Every panel should explain what it measures, where it comes from and when it was updated.'],
          'p5' => ['title' => 'Privacy', 'body' => 'Permissions, API keys and automations must stay explicit and governable.'],
          'p6' => ['title' => 'Resilience', 'body' => 'Trackers, retries, logs and monitors should make errors and runtime states readable.'],
          'p7' => ['title' => 'Simplicity', 'body' => 'Add power without adding confusion: fewer layers, clearer intent.'],
          'p8' => ['title' => 'Evolution', 'body' => 'Plugin today, cloud dashboard tomorrow, dedicated app when the runtime is mature.'],
          'p9' => ['title' => 'Openness', 'body' => 'Assets, templates and marketplace should encourage reuse, study and collaboration.'],
          'p10' => ['title' => 'Discipline', 'body' => 'Daily quality: document, test, refine and make the product clearer.'],
        ],
        'storyBadge' => 'Carlos Malleux',
        'story' => [
          'one' => 'Trackers Lens did not start as another generic app. It started as a need: controlling data sources, automations and interfaces without losing clarity.',
          'two' => 'Over time it grew by removing ambiguity: boxLens for visualization, boxTracker for collection, workspaces for composition, IndexedDB to keep the runtime close to the device.',
          'three' => 'The goal is not to create a closed box, but to make data more usable, direct and verifiable, with AI and automations serving the user.',
          'four' => 'Trackers Lens is the result of that process: a local-first ecosystem designed to become a professional app without giving up control.',
          'footer' => 'Trackers Lens is built with this energy: patient technical work, care for detail and quality as a daily direction.',
        ],
      ],
    ],
  ],
  'es' => [
    'locale' => 'es_ES',
    'meta' => [
      'title' => 'Trackers Lens — IA para Datos Realtime',
      'description' => 'Monitoriza APIs, WebSocket, RSS y datos realtime en el navegador. Crea dashboards, trackers IA y automatizaciones locales.',
    ],
    'accessibility' => ['skip' => 'Saltar al contenido', 'language' => 'Idioma'],
    'nav' => [
      'features' => 'Funcionalidades',
      'why' => 'Por que Trackers Lens',
      'marketplace' => 'Marketplace',
      'pricing' => 'Precios',
      'docs' => 'Documentacion',
      'login' => 'Acceder',
      'download' => 'Avisarme',
    ],
    'hero' => [
      'badge' => 'AI-powered • Privacy first • Open ecosystem',
      'title' => 'Tu centro de control para datos',
      'subtitle' => 'Monitoriza cualquier fuente de datos, en local o desde APIs publicas. Construye dashboards inteligentes, automatiza analisis y toma decisiones basadas en insights reales.',
      'ctaPrimary' => 'Avisarme del Lanzamiento',
      'ctaSecondary' => 'Ver Demo',
      'devLabel' => 'En desarrollo activo',
      'devStatus' => 'Plugin de navegador en preparacion',
      'devBody' => 'Estamos finalizando el runtime local, el marketplace y el paquete del plugin. La descarga estara disponible pronto.',
      'devProgress' => 'Progreso release',
      'trustPrivate' => '100% privado',
      'trustLocal' => 'Datos siempre locales',
      'trustOpen' => 'Open Source',
      'metricTrackers' => 'Trackers activos',
      'metricData' => 'Datos procesados',
      'metricInsights' => 'AI Insights',
      'metricActions' => 'Acciones automaticas',
      'chartActivity' => 'Actividad realtime',
      'chartResources' => 'Uso de recursos',
    ],
    'value' => [
      'title' => 'Potencia. Flexibilidad. Inteligencia.',
      'subtitle' => 'Todo en un unico ecosistema.',
      'cards' => [
        'monitor' => ['title' => 'Monitoriza todo', 'body' => 'Datos desde APIs, WebSocket, RSS, bases de datos, archivos y mucho mas. Todo en tiempo real.'],
        'ai' => ['title' => 'IA integrada', 'body' => 'Analisis inteligentes, resumenes automaticos y alertas predictivas impulsadas por IA.'],
        'automation' => ['title' => 'Automatizaciones', 'body' => 'Crea reglas, triggers y acciones automaticas basadas en tus datos y condiciones.'],
        'visual' => ['title' => 'Visualizaciones', 'body' => 'Dashboards personalizables para cada necesidad, de simples a avanzados.'],
        'privacy' => ['title' => 'Privacy First', 'body' => 'Ejecucion local, datos en tu dispositivo y ningun cloud obligatorio.'],
        'open' => ['title' => 'Ecosistema abierto', 'body' => 'Plugins, marketplace y componentes extensibles para construir tu workflow.'],
      ],
    ],
    'privacy' => [
      'badge' => 'Privacy First',
      'title' => 'Tus datos, tu control.',
      'body' => 'Sin cloud obligatorio. Trackers Lens ejecuta tus assets en el plugin del navegador, usa IndexedDB local y llama APIs directamente desde el dispositivo del usuario. Ningun servidor central debe ejecutar tus assets.',
      'pointCloud' => ['title' => 'Sin cloud obligatorio', 'body' => 'Sincroniza solo cuando quieras.'],
      'pointRuntime' => ['title' => 'Runtime local', 'body' => 'Ejecucion en el plugin del navegador.'],
      'pointDb' => ['title' => 'IndexedDB local', 'body' => 'Persistencia de datos en el dispositivo.'],
      'pointApi' => ['title' => 'APIs desde tu equipo', 'body' => 'Solicitudes originadas desde el cliente del usuario.'],
    ],
    'architecture' => [
      'title' => 'Tres pilares. Un ecosistema.',
      'site' => ['title' => 'Sitio web / marketplace', 'body' => 'Descubre, instala y comparte boxes, trackers, lenses y plantillas listas para tu flujo de trabajo.'],
      'plugin' => ['title' => 'Plugin browser runtime local', 'body' => 'Un entorno operativo en el navegador para ejecutar trackers, dashboards y automatizaciones cerca de los datos.'],
      'chromium' => ['title' => 'Futuro entorno dedicado Chromium fork', 'body' => 'Una base dedicada para runtimes avanzados, aislamiento, rendimiento y tooling profesional.'],
    ],
    'boxes' => [
      'title' => 'Construye con boxLens y boxTracker',
      'body' => 'boxLens gestiona visualizacion HTML, CSS y UI. boxTracker orquesta datos, APIs, WebSocket, RSS, IA y automatizaciones. Trackers y lenses se comunican mediante canales de datos claros y componibles.',
    ],
    'developers' => [
      'title' => 'Desarrolla. Extiende. Personaliza.',
      'body' => 'Trackers Lens es open source y esta pensado para desarrolladores. Crea tus boxes, integra tus APIs y contribuye al ecosistema.',
      'docs' => 'Documentacion',
      'api' => 'API Reference',
      'examples' => 'Ejemplos',
      'community' => 'Community',
    ],
    'stats' => ['users' => 'usuarios activos', 'trackers' => 'trackers creados', 'data' => 'datos procesados', 'uptime' => 'uptime local'],
    'pricing' => [
      'title' => 'Precios simples para empezar ahora.',
      'subtitle' => 'Empieza con el plugin gratuito y escala cuando tu ecosistema crezca.',
      'free' => ['label' => 'Free', 'price' => 'Gratis', 'body' => 'Runtime local, trackers personales, dashboards y marketplace publico.'],
      'pro' => ['label' => 'Pro', 'price' => 'Pronto', 'body' => 'Workspaces avanzados, automatizaciones potenciadas y herramientas para equipos profesionales.'],
      'enterprise' => ['label' => 'Enterprise', 'price' => 'Custom', 'body' => 'Despliegues dedicados, politicas de seguridad y soporte para entornos regulados.'],
    ],
    'cta' => [
      'title' => 'En desarrollo ahora. Lanzamiento pronto.',
      'download' => 'Avisarme del Lanzamiento',
      'demo' => 'Ver Demo',
      'note' => 'El plugin se podra descargar pronto. Sin registro requerido para seguir el lanzamiento.',
    ],
    'footer' => [
      'brandText' => 'El centro de control con IA para monitorizar, analizar y automatizar cualquier fuente de datos.',
      'product' => 'Producto',
      'features' => 'Funcionalidades',
      'pricing' => 'Pricing',
      'roadmap' => 'Roadmap',
      'changelog' => 'Changelog',
      'resources' => 'Recursos',
      'docs' => 'Documentacion',
      'api' => 'API Reference',
      'examples' => 'Ejemplos',
      'blog' => 'Blog',
      'company' => 'Empresa',
      'about' => 'Quienes somos',
      'contact' => 'Contacto',
      'privacy' => 'Privacy Policy',
      'terms' => 'Terminos de servicio',
      'newsletter' => 'Newsletter',
      'newsletterText' => 'Suscribete para novedades, actualizaciones y guias.',
      'emailPlaceholder' => 'Tu email',
      'newsletterSubmit' => 'Suscribirse',
      'copyright' => '© 2026 Trackers Lens. Todos los derechos reservados.',
    ],
    'auth' => [
      'close' => 'Cerrar login',
      'kicker' => 'Acceso dashboard',
      'loginTitle' => 'Accede a Trackers Lens',
      'loginBody' => 'Usa tu cuenta para entrar en el dashboard cloud y gestionar assets, boxes y workspaces.',
      'tabsLabel' => 'Modo de acceso',
      'loginTab' => 'Login',
      'registerTab' => 'Crear cuenta',
      'name' => 'Nombre',
      'email' => 'Email',
      'password' => 'Password',
      'passwordConfirmation' => 'Confirmar password',
      'remember' => 'Recordarme',
      'loginSubmit' => 'Acceder',
      'registerSubmit' => 'Crear cuenta',
      'connecting' => 'Conectando con la API...',
      'failed' => 'Acceso fallido. Revisa los datos e intentalo de nuevo.',
      'success' => 'Acceso correcto. Abriendo dashboard...',
      'saving' => 'Guardando...',
      'newsletterSaved' => 'Email guardado. Te avisaremos en el lanzamiento.',
    ],
    'launch' => [
      'close' => 'Cerrar aviso de lanzamiento',
      'kicker' => 'Lanzamiento pronto',
      'title' => 'Deja tu email',
      'body' => 'Te avisaremos cuando el plugin Trackers Lens este listo para descargar y cuando abramos los primeros accesos.',
      'submit' => 'Avisarme del lanzamiento',
      'note' => 'Sin spam. Solo actualizaciones importantes sobre releases, plugin y acceso anticipado.',
      'invalid' => 'Introduce un email valido.',
    ],
    'contact' => [
      'close' => 'Cerrar contacto',
      'kicker' => 'Contacto',
      'title' => 'Hablemos de Trackers Lens',
      'body' => 'Escribenos para acceso anticipado, partnerships, soporte o preguntas tecnicas sobre el runtime.',
      'message' => 'Mensaje',
      'submit' => 'Enviar mensaje',
      'note' => 'El mensaje se guarda de forma segura y se envia al equipo Trackers Lens.',
      'success' => 'Mensaje enviado. Te responderemos pronto.',
      'invalid' => 'Completa todos los campos requeridos.',
    ],
    'pages' => [
      'about' => [
        'metaTitle' => 'Quienes somos — Trackers Lens',
        'metaDescription' => 'Quienes somos Trackers Lens: manifiesto, principios y vision para un runtime local con IA, legible y controlable.',
        'badge' => 'Quienes somos',
        'title' => 'Datos diarios transformados en un runtime controlable.',
        'lead' => 'Trackers Lens nace de una decision simple y exigente: construir herramientas que sigan siendo legibles, locales y honestas mientras el proyecto crece.',
        'note' => 'No es solo un dashboard. Es una forma de trabajar: menos ruido, mas control, mas cuidado por el detalle. Cada tracker, lens y workspace debe reducir la distancia entre dato, decision e interfaz real.',
        'manifestoBadge' => 'Manifiesto',
        'manifestoTitle' => 'El manifiesto detras de Trackers Lens',
        'principles' => [
          'p1' => ['title' => 'Control', 'body' => 'El usuario debe ver donde viven los datos, que trackers se ejecutan y que se sincroniza.'],
          'p2' => ['title' => 'Local-first', 'body' => 'El runtime empieza en el navegador y en IndexedDB: cloud solo cuando realmente hace falta.'],
          'p3' => ['title' => 'Composicion', 'body' => 'boxLens, boxTracker y workspaces deben unirse sin convertirse en una estructura rigida.'],
          'p4' => ['title' => 'Precision', 'body' => 'Cada panel debe explicar que mide, de donde viene y cuando fue actualizado.'],
          'p5' => ['title' => 'Privacidad', 'body' => 'Permisos, API keys y automatizaciones deben seguir siendo explicitos y gobernables.'],
          'p6' => ['title' => 'Resiliencia', 'body' => 'Trackers, reintentos, logs y monitores deben hacer legibles los errores y estados del runtime.'],
          'p7' => ['title' => 'Simplicidad', 'body' => 'Agregar potencia sin agregar confusion: menos capas, mas intencion.'],
          'p8' => ['title' => 'Evolucion', 'body' => 'Plugin hoy, dashboard cloud manana, app dedicada cuando el runtime este maduro.'],
          'p9' => ['title' => 'Apertura', 'body' => 'Assets, plantillas y marketplace deben favorecer reutilizacion, estudio y colaboracion.'],
          'p10' => ['title' => 'Disciplina', 'body' => 'Calidad diaria: documentar, probar, pulir y hacer el producto mas claro.'],
        ],
        'storyBadge' => 'Carlos Malleux',
        'story' => [
          'one' => 'Trackers Lens no empezo como otra app generica. Empezo como una necesidad: controlar fuentes de datos, automatizaciones e interfaces sin perder claridad.',
          'two' => 'Con el tiempo crecio eliminando ambiguedad: boxLens para visualizar, boxTracker para recoger datos, workspaces para componer, IndexedDB para mantener el runtime cerca del dispositivo.',
          'three' => 'El objetivo no es crear una caja cerrada, sino hacer los datos mas usables, directos y verificables, con IA y automatizaciones al servicio del usuario.',
          'four' => 'Trackers Lens es el resultado de ese proceso: un ecosistema local-first pensado para convertirse en una app profesional sin renunciar al control.',
          'footer' => 'Trackers Lens se construye con esta energia: trabajo tecnico paciente, cuidado por el detalle y calidad como direccion diaria.',
        ],
      ],
    ],
  ],
];
