<?php

return [
    'it' => [
        'locale' => 'it_IT',
        'meta' => [
            'title' => 'Trackers Lens — AI per Dati Realtime',
            'description' => 'Monitora API, WebSocket, RSS e dati realtime nel browser. Crea dashboard, tracker AI e automazioni locali privacy-first.',
        ],
        'accessibility' => ['skip' => 'Salta al contenuto', 'language' => 'Lingua'],
        'nav' => [
            'features' => 'Funzionalita',
            'why' => 'Perche Trackers Lens',
            'marketplace' => 'Marketplace',
            'pricing' => 'Prezzi',
            'docs' => 'Documentazione',
            'login' => 'Accedi',
            'download' => 'Avvisami',
        ],
        'hero' => [
            'badge' => 'AI-powered • Privacy first • Open ecosystem',
            'title' => 'Il tuo centro di controllo per i dati',
            'subtitle' => 'Monitora qualsiasi fonte di dati, in locale o da API pubbliche. Costruisci dashboard intelligenti, automatizza analisi e prendi decisioni basate su insight reali.',
            'ctaPrimary' => 'Avvisami al Lancio',
            'ctaSecondary' => 'Guarda la Demo',
            'devLabel' => 'In sviluppo attivo',
            'devStatus' => 'Plugin browser in preparazione',
            'devBody' => 'Stiamo finalizzando runtime locale, marketplace e pacchetto plugin. Il download sara disponibile presto.',
            'devProgress' => 'Progress release',
            'trustPrivate' => '100% privato',
            'trustLocal' => 'Dati sempre locali',
            'trustOpen' => 'Open Source',
            'metricTrackers' => 'Tracker attivi',
            'metricData' => 'Dati processati',
            'metricInsights' => 'AI Insights',
            'metricActions' => 'Azioni automatiche',
            'chartActivity' => 'Attivita realtime',
            'chartResources' => 'Utilizzo risorse',
        ],
        'value' => [
            'title' => 'Potenza. Flessibilita. Intelligenza.',
            'subtitle' => 'Tutto in un unico ecosistema.',
            'cards' => [
                'monitor' => ['title' => 'Monitora tutto', 'body' => 'Dati da API, WebSocket, RSS, database, file e molto altro. Tutto in tempo reale.'],
                'ai' => ['title' => 'AI Integrata', 'body' => 'Analisi intelligenti, sintesi automatiche e alert predittivi alimentati dall\'AI.'],
                'automation' => ['title' => 'Automazioni', 'body' => 'Crea regole, trigger e azioni automatiche basate sui tuoi dati e condizioni.'],
                'visual' => ['title' => 'Visualizzazioni', 'body' => 'Dashboard personalizzabili per ogni esigenza. Da semplici a avanzate.'],
                'privacy' => ['title' => 'Privacy First', 'body' => 'Esecuzione locale, dati sul tuo dispositivo e nessun cloud obbligatorio.'],
                'open' => ['title' => 'Ecosistema Aperto', 'body' => 'Plugin, marketplace e componenti estendibili per costruire il tuo workflow.'],
            ],
        ],
        'privacy' => [
            'badge' => 'Privacy First',
            'title' => 'I tuoi dati, il tuo controllo.',
            'body' => 'Nessun cloud obbligatorio. Trackers Lens esegue i tuoi asset nel plugin browser, usa IndexedDB locale e chiama API direttamente dal dispositivo utente. Nessun server centrale deve eseguire i tuoi asset.',
            'pointCloud' => ['title' => 'Nessun cloud obbligatorio', 'body' => 'Sincronizzi solo quando vuoi.'],
            'pointRuntime' => ['title' => 'Runtime locale', 'body' => 'Esecuzione nel plugin browser.'],
            'pointDb' => ['title' => 'IndexedDB locale', 'body' => 'Persistenza dati sul dispositivo.'],
            'pointApi' => ['title' => 'API dal tuo device', 'body' => 'Richieste originate dal client utente.'],
        ],
        'architecture' => [
            'title' => 'Tre pilastri. Un ecosistema.',
            'site' => ['title' => 'Sito web / marketplace', 'body' => 'Scopri, installa e condividi box, tracker, lens e modelli pronti per il tuo flusso di lavoro.'],
            'plugin' => ['title' => 'Plugin browser runtime locale', 'body' => 'Un ambiente operativo nel browser per eseguire tracker, dashboard e automazioni vicino ai dati.'],
            'chromium' => ['title' => 'Futuro ambiente dedicato Chromium fork', 'body' => 'Una base dedicata per runtime avanzati, isolamento, performance e tooling professionale.'],
        ],
        'boxes' => [
            'title' => 'Costruisci con boxLens e boxTracker',
            'body' => 'boxLens gestisce visualizzazione HTML, CSS e UI. boxTracker orchestra dati, API, WebSocket, RSS, AI e automazioni. Tracker e lens comunicano tramite canali dati chiari e componibili.',
        ],
        'developers' => [
            'title' => 'Sviluppa. Estendi. Personalizza.',
            'body' => 'Trackers Lens e open source e pensato per gli sviluppatori. Crea i tuoi box, integra le tue API e contribuisci all\'ecosistema.',
            'docs' => 'Documentazione',
            'api' => 'API Reference',
            'examples' => 'Esempi',
            'community' => 'Community',
        ],
        'stats' => ['users' => 'utenti attivi', 'trackers' => 'tracker creati', 'data' => 'dati elaborati', 'uptime' => 'uptime locale'],
        'pricing' => [
            'title' => 'Prezzi semplici per partire subito.',
            'subtitle' => 'Inizia con il plugin gratuito e scala quando il tuo ecosistema cresce.',
            'free' => ['label' => 'Free', 'price' => 'Gratis', 'body' => 'Runtime locale, tracker personali, dashboard e marketplace pubblico.'],
            'pro' => ['label' => 'Pro', 'price' => 'Presto', 'body' => 'Workspace avanzati, automazioni potenziate e strumenti per team professionali.'],
            'enterprise' => ['label' => 'Enterprise', 'price' => 'Custom', 'body' => 'Distribuzioni dedicate, policy di sicurezza e supporto per ambienti regolati.'],
        ],
        'cta' => [
            'title' => 'In sviluppo ora. Lancio in arrivo.',
            'download' => 'Avvisami al Lancio',
            'demo' => 'Guarda la Demo',
            'note' => 'Il plugin sara scaricabile presto. Nessuna registrazione richiesta per seguire il lancio.',
        ],
        'footer' => [
            'brandText' => 'Il centro di controllo AI-powered per monitorare, analizzare e automatizzare qualsiasi fonte di dati.',
            'product' => 'Prodotto',
            'features' => 'Funzionalita',
            'pricing' => 'Pricing',
            'roadmap' => 'Roadmap',
            'changelog' => 'Changelog',
            'resources' => 'Risorse',
            'docs' => 'Documentazione',
            'api' => 'API Reference',
            'examples' => 'Esempi',
            'blog' => 'Blog',
            'company' => 'Azienda',
            'about' => 'Chi siamo',
            'contact' => 'Contatti',
            'privacy' => 'Privacy Policy',
            'terms' => 'Termini di servizio',
            'newsletter' => 'Newsletter',
            'newsletterText' => 'Iscriviti alla newsletter per novita, aggiornamenti e guide.',
            'emailPlaceholder' => 'La tua email',
            'copyright' => '© 2026 Trackers Lens. Tutti i diritti riservati.',
        ],
    ],
    'en' => [
        'locale' => 'en_US',
        'meta' => [
            'title' => 'Trackers Lens — Local AI Data Monitoring',
            'description' => 'Monitor APIs, WebSocket, RSS and realtime data in your browser. Build AI dashboards, smart trackers and local automation.',
        ],
        'accessibility' => ['skip' => 'Skip to content', 'language' => 'Language'],
        'nav' => [
            'features' => 'Features',
            'why' => 'Why Trackers Lens',
            'marketplace' => 'Marketplace',
            'pricing' => 'Pricing',
            'docs' => 'Docs',
            'login' => 'Login',
            'download' => 'Notify Me',
        ],
        'hero' => [
            'badge' => 'AI-powered • Privacy first • Open ecosystem',
            'title' => 'Your data control center',
            'subtitle' => 'Monitor any data source locally or from public APIs. Build intelligent dashboards, automate analysis and make decisions based on real insights.',
            'ctaPrimary' => 'Notify Me at Launch',
            'ctaSecondary' => 'Watch Demo',
            'devLabel' => 'In active development',
            'devStatus' => 'Browser plugin in preparation',
            'devBody' => 'We are finalizing the local runtime, marketplace and plugin package. Download access is coming soon.',
            'devProgress' => 'Release progress',
            'trustPrivate' => '100% private',
            'trustLocal' => 'Always local data',
            'trustOpen' => 'Open Source',
            'metricTrackers' => 'Active trackers',
            'metricData' => 'Processed data',
            'metricInsights' => 'AI Insights',
            'metricActions' => 'Automated actions',
            'chartActivity' => 'Realtime activity',
            'chartResources' => 'Resource usage',
        ],
        'value' => [
            'title' => 'Power. Flexibility. Intelligence.',
            'subtitle' => 'Everything in one ecosystem.',
            'cards' => [
                'monitor' => ['title' => 'Monitor everything', 'body' => 'Data from APIs, WebSocket, RSS, databases, files and more. All in real time.'],
                'ai' => ['title' => 'Integrated AI', 'body' => 'Smart analysis, automatic summaries and predictive alerts powered by AI.'],
                'automation' => ['title' => 'Automations', 'body' => 'Create rules, triggers and automatic actions based on your data and conditions.'],
                'visual' => ['title' => 'Visualizations', 'body' => 'Custom dashboards for every need, from simple views to advanced interfaces.'],
                'privacy' => ['title' => 'Privacy First', 'body' => 'Local execution, data on your device and no mandatory cloud.'],
                'open' => ['title' => 'Open Ecosystem', 'body' => 'Plugins, marketplace and extensible components for building your workflow.'],
            ],
        ],
        'privacy' => [
            'badge' => 'Privacy First',
            'title' => 'Your data, your control.',
            'body' => 'No mandatory cloud. Trackers Lens runs your assets inside the browser plugin, uses local IndexedDB and calls APIs directly from the user\'s device. No central server has to execute your assets.',
            'pointCloud' => ['title' => 'No mandatory cloud', 'body' => 'Sync only when you choose.'],
            'pointRuntime' => ['title' => 'Local runtime', 'body' => 'Execution inside the browser plugin.'],
            'pointDb' => ['title' => 'Local IndexedDB', 'body' => 'Data persistence on the device.'],
            'pointApi' => ['title' => 'APIs from your device', 'body' => 'Requests originate from the user client.'],
        ],
        'architecture' => [
            'title' => 'Three pillars. One ecosystem.',
            'site' => ['title' => 'Website / marketplace', 'body' => 'Discover, install and share boxes, trackers, lenses and templates ready for your workflow.'],
            'plugin' => ['title' => 'Local browser plugin runtime', 'body' => 'An operating environment in the browser to run trackers, dashboards and automations near the data.'],
            'chromium' => ['title' => 'Future dedicated Chromium fork', 'body' => 'A dedicated base for advanced runtimes, isolation, performance and professional tooling.'],
        ],
        'boxes' => [
            'title' => 'Build with boxLens and boxTracker',
            'body' => 'boxLens handles HTML, CSS and UI visualization. boxTracker orchestrates data, APIs, WebSocket, RSS, AI and automations. Trackers and lenses communicate through clear, composable data channels.',
        ],
        'developers' => [
            'title' => 'Develop. Extend. Customize.',
            'body' => 'Trackers Lens is open source and built for developers. Create your own boxes, integrate your APIs and contribute to the ecosystem.',
            'docs' => 'Documentation',
            'api' => 'API Reference',
            'examples' => 'Examples',
            'community' => 'Community',
        ],
        'stats' => ['users' => 'active users', 'trackers' => 'trackers created', 'data' => 'data points processed', 'uptime' => 'local uptime'],
        'pricing' => [
            'title' => 'Simple pricing to start now.',
            'subtitle' => 'Start with the free plugin and scale when your ecosystem grows.',
            'free' => ['label' => 'Free', 'price' => 'Free', 'body' => 'Local runtime, personal trackers, dashboards and public marketplace.'],
            'pro' => ['label' => 'Pro', 'price' => 'Soon', 'body' => 'Advanced workspaces, stronger automations and tools for professional teams.'],
            'enterprise' => ['label' => 'Enterprise', 'price' => 'Custom', 'body' => 'Dedicated deployments, security policies and support for regulated environments.'],
        ],
        'cta' => [
            'title' => 'In development now. Launch coming soon.',
            'download' => 'Notify Me at Launch',
            'demo' => 'Watch Demo',
            'note' => 'The plugin will be available soon. No registration required to follow the launch.',
        ],
        'footer' => [
            'brandText' => 'The AI-powered control center to monitor, analyze and automate any data source.',
            'product' => 'Product',
            'features' => 'Features',
            'pricing' => 'Pricing',
            'roadmap' => 'Roadmap',
            'changelog' => 'Changelog',
            'resources' => 'Resources',
            'docs' => 'Documentation',
            'api' => 'API Reference',
            'examples' => 'Examples',
            'blog' => 'Blog',
            'company' => 'Company',
            'about' => 'About',
            'contact' => 'Contact',
            'privacy' => 'Privacy Policy',
            'terms' => 'Terms of Service',
            'newsletter' => 'Newsletter',
            'newsletterText' => 'Subscribe for news, updates and guides.',
            'emailPlaceholder' => 'Your email',
            'copyright' => '© 2026 Trackers Lens. All rights reserved.',
        ],
    ],
    'es' => [
        'locale' => 'es_ES',
        'meta' => [
            'title' => 'Trackers Lens — IA para Datos Realtime',
            'description' => 'Monitoriza APIs, WebSocket, RSS y datos realtime en el navegador. Crea dashboards, trackers IA y automatizaciones locales.',
        ],
        'accessibility' => ['skip' => 'Saltar al contenido', 'language' => 'Idioma'],
        'nav' => [
            'features' => 'Funcionalidades',
            'why' => 'Por que Trackers Lens',
            'marketplace' => 'Marketplace',
            'pricing' => 'Precios',
            'docs' => 'Documentacion',
            'login' => 'Acceder',
            'download' => 'Avisarme',
        ],
        'hero' => [
            'badge' => 'AI-powered • Privacy first • Open ecosystem',
            'title' => 'Tu centro de control para datos',
            'subtitle' => 'Monitoriza cualquier fuente de datos, en local o desde APIs publicas. Construye dashboards inteligentes, automatiza analisis y toma decisiones basadas en insights reales.',
            'ctaPrimary' => 'Avisarme del Lanzamiento',
            'ctaSecondary' => 'Ver Demo',
            'devLabel' => 'En desarrollo activo',
            'devStatus' => 'Plugin de navegador en preparacion',
            'devBody' => 'Estamos finalizando el runtime local, el marketplace y el paquete del plugin. La descarga estara disponible pronto.',
            'devProgress' => 'Progreso release',
            'trustPrivate' => '100% privado',
            'trustLocal' => 'Datos siempre locales',
            'trustOpen' => 'Open Source',
            'metricTrackers' => 'Trackers activos',
            'metricData' => 'Datos procesados',
            'metricInsights' => 'AI Insights',
            'metricActions' => 'Acciones automaticas',
            'chartActivity' => 'Actividad realtime',
            'chartResources' => 'Uso de recursos',
        ],
        'value' => [
            'title' => 'Potencia. Flexibilidad. Inteligencia.',
            'subtitle' => 'Todo en un unico ecosistema.',
            'cards' => [
                'monitor' => ['title' => 'Monitoriza todo', 'body' => 'Datos desde APIs, WebSocket, RSS, bases de datos, archivos y mucho mas. Todo en tiempo real.'],
                'ai' => ['title' => 'IA integrada', 'body' => 'Analisis inteligentes, resumenes automaticos y alertas predictivas impulsadas por IA.'],
                'automation' => ['title' => 'Automatizaciones', 'body' => 'Crea reglas, triggers y acciones automaticas basadas en tus datos y condiciones.'],
                'visual' => ['title' => 'Visualizaciones', 'body' => 'Dashboards personalizables para cada necesidad, de simples a avanzados.'],
                'privacy' => ['title' => 'Privacy First', 'body' => 'Ejecucion local, datos en tu dispositivo y ningun cloud obligatorio.'],
                'open' => ['title' => 'Ecosistema abierto', 'body' => 'Plugins, marketplace y componentes extensibles para construir tu workflow.'],
            ],
        ],
        'privacy' => [
            'badge' => 'Privacy First',
            'title' => 'Tus datos, tu control.',
            'body' => 'Sin cloud obligatorio. Trackers Lens ejecuta tus assets en el plugin del navegador, usa IndexedDB local y llama APIs directamente desde el dispositivo del usuario. Ningun servidor central debe ejecutar tus assets.',
            'pointCloud' => ['title' => 'Sin cloud obligatorio', 'body' => 'Sincroniza solo cuando quieras.'],
            'pointRuntime' => ['title' => 'Runtime local', 'body' => 'Ejecucion en el plugin del navegador.'],
            'pointDb' => ['title' => 'IndexedDB local', 'body' => 'Persistencia de datos en el dispositivo.'],
            'pointApi' => ['title' => 'APIs desde tu equipo', 'body' => 'Solicitudes originadas desde el cliente del usuario.'],
        ],
        'architecture' => [
            'title' => 'Tres pilares. Un ecosistema.',
            'site' => ['title' => 'Sitio web / marketplace', 'body' => 'Descubre, instala y comparte boxes, trackers, lenses y plantillas listas para tu flujo de trabajo.'],
            'plugin' => ['title' => 'Plugin browser runtime local', 'body' => 'Un entorno operativo en el navegador para ejecutar trackers, dashboards y automatizaciones cerca de los datos.'],
            'chromium' => ['title' => 'Futuro entorno dedicado Chromium fork', 'body' => 'Una base dedicada para runtimes avanzados, aislamiento, rendimiento y tooling profesional.'],
        ],
        'boxes' => [
            'title' => 'Construye con boxLens y boxTracker',
            'body' => 'boxLens gestiona visualizacion HTML, CSS y UI. boxTracker orquesta datos, APIs, WebSocket, RSS, IA y automatizaciones. Trackers y lenses se comunican mediante canales de datos claros y componibles.',
        ],
        'developers' => [
            'title' => 'Desarrolla. Extiende. Personaliza.',
            'body' => 'Trackers Lens es open source y esta pensado para desarrolladores. Crea tus boxes, integra tus APIs y contribuye al ecosistema.',
            'docs' => 'Documentacion',
            'api' => 'API Reference',
            'examples' => 'Ejemplos',
            'community' => 'Community',
        ],
        'stats' => ['users' => 'usuarios activos', 'trackers' => 'trackers creados', 'data' => 'datos procesados', 'uptime' => 'uptime local'],
        'pricing' => [
            'title' => 'Precios simples para empezar ahora.',
            'subtitle' => 'Empieza con el plugin gratuito y escala cuando tu ecosistema crezca.',
            'free' => ['label' => 'Free', 'price' => 'Gratis', 'body' => 'Runtime local, trackers personales, dashboards y marketplace publico.'],
            'pro' => ['label' => 'Pro', 'price' => 'Pronto', 'body' => 'Workspaces avanzados, automatizaciones potenciadas y herramientas para equipos profesionales.'],
            'enterprise' => ['label' => 'Enterprise', 'price' => 'Custom', 'body' => 'Despliegues dedicados, politicas de seguridad y soporte para entornos regulados.'],
        ],
        'cta' => [
            'title' => 'En desarrollo ahora. Lanzamiento pronto.',
            'download' => 'Avisarme del Lanzamiento',
            'demo' => 'Ver Demo',
            'note' => 'El plugin se podra descargar pronto. Sin registro requerido para seguir el lanzamiento.',
        ],
        'footer' => [
            'brandText' => 'El centro de control con IA para monitorizar, analizar y automatizar cualquier fuente de datos.',
            'product' => 'Producto',
            'features' => 'Funcionalidades',
            'pricing' => 'Pricing',
            'roadmap' => 'Roadmap',
            'changelog' => 'Changelog',
            'resources' => 'Recursos',
            'docs' => 'Documentacion',
            'api' => 'API Reference',
            'examples' => 'Ejemplos',
            'blog' => 'Blog',
            'company' => 'Empresa',
            'about' => 'Quienes somos',
            'contact' => 'Contacto',
            'privacy' => 'Privacy Policy',
            'terms' => 'Terminos de servicio',
            'newsletter' => 'Newsletter',
            'newsletterText' => 'Suscribete para novedades, actualizaciones y guias.',
            'emailPlaceholder' => 'Tu email',
            'copyright' => '© 2026 Trackers Lens. Todos los derechos reservados.',
        ],
    ],
];
