<?php

return [
  'it' => [
    'locale' => 'it_IT',
    'meta' => [
      'title' => 'Trackers Lens — La tua app per dati, Python e AI',
      'description' => 'Collega dati, nodi e modelli AI in un’app desktop. Flow Map, runtime JavaScript e Python, ricerca sui documenti e archiviazione locale SQLite.',
    ],
    'accessibility' => [
      'skip' => 'Salta al contenuto',
      'language' => 'Lingua',
    ],
    'nav' => [
      'features' => 'Funzionalita',
      'why' => 'Perche Trackers Lens',
      'marketplace' => 'Runtime',
      'pricing' => 'Prezzi',
      'docs' => 'Documentazione',
      'login' => 'Accedi',
      'download' => 'Avvisami',
    ],
    'hero' => [
      'badge' => 'App desktop · Python · Node.js · Modelli AI',
      'title' => 'Dati, automazioni e AI. Nella tua app.',
      'subtitle' => 'Trackers Lens è il tuo ambiente operativo AI locale. Collega sorgenti, nodi e modelli in Flow Map, lavora con Python e JavaScript e segui ogni esecuzione dal tuo desktop.',
      'ctaPrimary' => 'Avvisami al Lancio',
      'ctaSecondary' => 'Esplora il flusso',
      'devLabel' => 'In sviluppo attivo',
      'devStatus' => 'App desktop in sviluppo',
      'devBody' => 'Il runtime desktop è già in sviluppo attivo. Iscriviti per ricevere aggiornamenti sulle release e sulla disponibilità del download.',
      'devProgress' => 'Progress release',
      'trustPrivate' => 'Permessi espliciti',
      'trustLocal' => 'Dati locali con SQLite',
      'trustOpen' => 'Modelli a tua scelta',
      'metricTrackers' => 'Tracker attivi',
      'metricData' => 'Dati processati',
      'metricInsights' => 'AI Insights',
      'metricActions' => 'Azioni automatiche',
      'chartActivity' => 'Attivita realtime',
      'chartResources' => 'Utilizzo risorse',
      'previewLabel' => 'Esempio di workflow nell’app',
      'previewTitle' => 'Dai documenti a una risposta verificabile',
      'previewNote' => 'Schema illustrativo: pacchetti e modelli vengono configurati nell’app.',
      'source' => 'Documenti',
      'retrieval' => 'Ricerca RAG',
      'agent' => 'Agente AI',
      'output' => 'Risposta e fonti',
      'control' => 'Esecuzioni, log e provenienza ispezionabili',
    ],
    'value' => [
      'title' => 'Un ambiente per costruire e far lavorare l’AI.',
      'subtitle' => 'Dal dato al modello, con strumenti che lavorano insieme.',
      'cards' => [
        'monitor' => [
          'title' => 'Flow Map e nodi',
          'body' => 'Collega sorgenti, processori, agenti, memoria e azioni. Vedi canali, dipendenze e stato del flusso nello stesso spazio.',
        ],
        'ai' => [
          'title' => 'Modelli AI locali ed esterni',
          'body' => 'Configura provider, modelli e prompt nell’AI Center. Usa Ollama, LM Studio o i provider API e Login supportati.',
        ],
        'automation' => [
          'title' => 'Python gestito',
          'body' => 'Installa i pacchetti previsti dall’app per embedding, ricerca RAG, reranking e analisi del testo. Ambienti e modelli hanno uno stato visibile.',
        ],
        'visual' => [
          'title' => 'Conoscenza dai documenti',
          'body' => 'Organizza documenti, chunk, memoria e relazioni. Ispeziona le fonti e gli output che alimentano gli agenti.',
        ],
        'privacy' => [
          'title' => 'Controllo locale',
          'body' => 'Workspace e dati del runtime risiedono in SQLite sul dispositivo. Le connessioni esterne dipendono dai servizi che scegli di usare.',
        ],
        'open' => [
          'title' => 'Nodi estendibili',
          'body' => 'Crea e importa Custom Node, verifica configurazione e permessi e attivali nel runtime sandbox disponibile nell’app.',
        ],
      ],
    ],
    'privacy' => [
      'badge' => 'Privacy First',
      'title' => 'I tuoi dati, il tuo controllo.',
      'body' => 'Il lavoro parte dal tuo dispositivo: l’app desktop gestisce workspace, flussi e persistenza SQLite. Per l’AI puoi scegliere modelli locali o servizi esterni. I dati inviati a un provider dipendono dalle connessioni e dalle operazioni che autorizzi.',
      'pointCloud' => [
        'title' => 'Nessun cloud obbligatorio',
        'body' => 'Il runtime locale non richiede un servizio cloud TL.',
      ],
      'pointRuntime' => [
        'title' => 'Runtime locale',
        'body' => 'Esecuzione nell’app desktop.',
      ],
      'pointDb' => [
        'title' => 'SQLite locale',
        'body' => 'Dati persistenti gestiti da TL Core.',
      ],
      'pointApi' => [
        'title' => 'Connessioni consapevoli',
        'body' => 'Scegli provider, sorgenti e permessi.',
      ],
    ],
    'architecture' => [
      'title' => 'Python, Node.js e AI nello stesso ambiente.',
      'site' => [
        'title' => 'Python e modelli gestiti',
        'body' => 'Pacchetti dedicati a embedding, RAG e NLP. L’app mostra requisiti e stato dei modelli e richiede conferma prima di installarli.',
      ],
      'plugin' => [
        'title' => 'Node.js e JavaScript',
        'body' => 'Electron e Node.js sostengono l’app desktop e TL Core. I nodi JavaScript elaborano dati e automazioni tramite il runtime e i suoi canali.',
      ],
      'chromium' => [
        'title' => 'Modelli e agenti AI',
        'body' => 'Separa la connessione al provider dalle impostazioni del singolo nodo. Scegli modello, prompt e opzioni supportate per ogni attività.',
      ],
    ],
    'boxes' => [
      'title' => 'Componi il tuo flusso, segui ogni passaggio.',
      'body' => 'In Flow Map ogni nodo ha un ruolo: acquisire dati, trasformarli, interrogare la conoscenza o eseguire un’azione. Canali, log e anteprime rendono visibile ciò che accade. I boxLens portano i risultati nei tuoi workspace.',
    ],
    'developers' => [
      'title' => 'Sviluppa. Estendi. Personalizza.',
      'body' => 'Parti dai nodi dell’app, configura i pacchetti Python e costruisci componenti riutilizzabili. I Custom Node dichiarano porte, impostazioni e permessi: puoi esaminarli prima di attivarli.',
      'docs' => 'Documentazione',
      'api' => 'API Reference',
      'examples' => 'Esempi',
      'community' => 'Community',
      'example' => 'Un flusso da comporre in Flow Map',
    ],
    'stats' => [
      'users' => 'ambiente desktop',
      'trackers' => 'pacchetti gestiti',
      'data' => 'modelli locali o esterni',
      'uptime' => 'persistenza locale',
    ],
    'pricing' => [
      'title' => 'Un’app in evoluzione. Piani in definizione.',
      'subtitle' => 'Disponibilità e condizioni saranno pubblicate insieme alle release dell’app.',
      'free' => [
        'label' => 'App desktop',
        'price' => 'In sviluppo',
        'body' => 'Flow Map, dati locali, runtime e connessioni AI nell’app TL.',
      ],
      'pro' => [
        'label' => 'Pro',
        'price' => 'Presto',
        'body' => 'Servizi aggiuntivi e collaborazione sono parte dell’evoluzione del prodotto.',
      ],
      'enterprise' => [
        'label' => 'Enterprise',
        'price' => 'Custom',
        'body' => 'Parliamo delle tue esigenze di integrazione e distribuzione.',
      ],
    ],
    'cta' => [
      'title' => 'In sviluppo ora. Lancio in arrivo.',
      'download' => 'Avvisami al Lancio',
      'demo' => 'Esplora il flusso',
      'note' => 'Iscriviti per conoscere le prossime release e la disponibilità dell’app desktop.',
    ],
    'footer' => [
      'brandText' => 'L’ambiente operativo AI locale per collegare dati, Python, nodi e modelli in un’app desktop.',
      'product' => 'Prodotto',
      'features' => 'Funzionalita',
      'pricing' => 'Pricing',
      'roadmap' => 'Roadmap',
      'changelog' => 'Changelog',
      'resources' => 'Risorse',
      'docs' => 'Documentazione',
      'api' => 'API Reference',
      'examples' => 'Esempi',
      'blog' => 'Blog',
      'company' => 'Azienda',
      'about' => 'Chi siamo',
      'contact' => 'Contatti',
      'privacy' => 'Privacy Policy',
      'terms' => 'Termini di servizio',
      'newsletter' => 'Newsletter',
      'newsletterText' => 'Iscriviti alla newsletter per novita, aggiornamenti e guide.',
      'emailPlaceholder' => 'La tua email',
      'newsletterSubmit' => 'Iscriviti',
      'copyright' => '© 2026 Trackers Lens. Tutti i diritti riservati.',
    ],
    'auth' => [
      'close' => 'Chiudi login',
      'kicker' => 'Accesso dashboard',
      'loginTitle' => 'Accedi a Trackers Lens',
      'loginBody' => 'Accedi all’area web di Trackers Lens. Il runtime desktop e i suoi dati locali sono gestiti dall’app.',
      'tabsLabel' => 'Modalita accesso',
      'loginTab' => 'Login',
      'registerTab' => 'Crea account',
      'name' => 'Nome',
      'email' => 'Email',
      'password' => 'Password',
      'passwordConfirmation' => 'Conferma password',
      'remember' => 'Ricordami',
      'loginSubmit' => 'Accedi',
      'registerSubmit' => 'Crea account',
      'connecting' => 'Connessione all\'API...',
      'failed' => 'Accesso non riuscito. Controlla i dati e riprova.',
      'success' => 'Accesso riuscito. Apertura dashboard...',
      'saving' => 'Salvataggio...',
      'newsletterSaved' => 'Email salvata. Ti avviseremo al lancio.',
    ],
    'launch' => [
      'close' => 'Chiudi avviso lancio',
      'kicker' => 'Lancio in arrivo',
      'title' => 'Lascia la tua email',
      'body' => 'Ti avviseremo delle release di Trackers Lens App e della disponibilità del download.',
      'submit' => 'Avvisami al lancio',
      'note' => 'Solo novità sull’app, release e accesso anticipato.',
      'invalid' => 'Inserisci una email valida.',
    ],
    'contact' => [
      'close' => 'Chiudi contatti',
      'kicker' => 'Contatti',
      'title' => 'Parliamo di Trackers Lens',
      'body' => 'Scrivici per accesso anticipato, partnership, supporto o domande tecniche sul runtime.',
      'message' => 'Messaggio',
      'submit' => 'Invia messaggio',
      'note' => 'Il messaggio viene salvato in modo sicuro e inviato al team Trackers Lens.',
      'success' => 'Messaggio inviato. Ti risponderemo presto.',
      'invalid' => 'Compila tutti i campi richiesti.',
    ],
    'pages' => [
      'about' => [
        'metaTitle' => 'Chi siamo — Trackers Lens',
        'metaDescription' => 'Chi siamo Trackers Lens: manifesto, principi e visione per un runtime locale AI-powered, leggibile e controllabile.',
        'badge' => 'Chi siamo',
        'title' => 'Dati quotidiani trasformati in un runtime controllabile.',
        'lead' => 'Trackers Lens nasce da una scelta semplice e impegnativa: costruire strumenti che restano leggibili, locali e onesti mentre il progetto cresce.',
        'note' => 'Non e solo una dashboard. E un modo di lavorare: meno rumore, piu controllo, piu cura per il dettaglio. Ogni tracker, lens e workspace deve ridurre la distanza tra dato, decisione e interfaccia reale.',
        'manifestoBadge' => 'Manifesto',
        'manifestoTitle' => 'Il manifesto dietro Trackers Lens',
        'principles' => [
          'p1' => [
            'title' => 'Controllo',
            'body' => 'L utente deve vedere dove vivono i dati, quali tracker girano e cosa viene sincronizzato.',
          ],
          'p2' => [
            'title' => 'Local-first',
            'body' => 'Il runtime vive nell’app desktop e i dati sono persistiti in SQLite. I servizi esterni sono una scelta esplicita.',
          ],
          'p3' => [
            'title' => 'Componibilita',
            'body' => 'boxLens, boxTracker e workspace devono unirsi senza diventare una struttura rigida.',
          ],
          'p4' => [
            'title' => 'Precisione',
            'body' => 'Ogni pannello deve spiegare cosa misura, da dove arriva e quando e stato aggiornato.',
          ],
          'p5' => [
            'title' => 'Privacy',
            'body' => 'Permessi, API keys e automazioni devono restare espliciti e governabili.',
          ],
          'p6' => [
            'title' => 'Resilienza',
            'body' => 'Tracker, retry, log e monitor devono rendere leggibili errori e stati runtime.',
          ],
          'p7' => [
            'title' => 'Semplicita',
            'body' => 'Aggiungere potenza senza aggiungere confusione: meno layer, piu intenzione.',
          ],
          'p8' => [
            'title' => 'Evoluzione',
            'body' => 'L’app cresce con runtime Python, nodi estendibili e modelli AI configurabili.',
          ],
          'p9' => [
            'title' => 'Apertura',
            'body' => 'Componenti e pacchetti riutilizzabili aiutano a condividere il lavoro. Il marketplace è una direzione futura.',
          ],
          'p10' => [
            'title' => 'Disciplina',
            'body' => 'Qualita quotidiana: documentare, testare, limare e rendere il prodotto piu chiaro.',
          ],
        ],
        'storyBadge' => 'Carlos Malleux',
        'story' => [
          'one' => 'Trackers Lens non e partito come un altra app generica. E partito come un bisogno: controllare fonti dati, automazioni e interfacce senza perdere chiarezza.',
          'two' => 'Oggi Flow Map collega nodi e canali; TL Core gestisce i dati locali; Python e i modelli AI estendono ciò che puoi costruire.',
          'three' => 'L obiettivo non e creare una scatola chiusa, ma rendere i dati piu usabili, diretti e verificabili, con AI e automazioni al servizio dell utente.',
          'four' => 'Trackers Lens è oggi un’app desktop in sviluppo, con un ambiente operativo locale dedicato a dati, conoscenza e automazioni AI.',
          'footer' => 'Trackers Lens e costruito con questa energia: lavoro tecnico paziente, cura per il dettaglio e qualita come direzione quotidiana.',
        ],
      ],
      'features' => [
        'metaTitle' => 'Funzionalità dell’app — Trackers Lens',
        'metaDescription' => 'Esplora Flow Map, Python gestito, Node.js, modelli AI, conoscenza e SQLite nell’app desktop Trackers Lens.',
        'badge' => 'L’ambiente operativo TL',
        'title' => 'Costruisci con dati, nodi e modelli.',
        'subtitle' => 'Un’app desktop per comporre flussi, eseguire analisi e collegare l’AI alle tue sorgenti. Python, JavaScript e modelli lavorano dentro un ambiente ispezionabile.',
        'futureTitle' => 'Un runtime che puoi seguire.',
        'futureBody' => 'Apri un workspace, collega i nodi in Flow Map e controlla input, output e log. Per i pacchetti gestiti l’app mostra requisiti e installazione; per i modelli AI scegli connessione e impostazioni del nodo.',
        'step1' => 'Componi il flusso',
        'step2' => 'Configura runtime e modelli',
        'step3' => 'Esegui e ispeziona',
        'cards' => [
          'plugin' => [
            'title' => 'Flow Map e nodi',
            'body' => 'Collega sorgenti, processori, agenti, memoria e azioni. Vedi canali, dipendenze e stato del flusso nello stesso spazio.',
          ],
          'workspace' => [
            'title' => 'Python gestito',
            'body' => 'Installa i pacchetti previsti dall’app per embedding, ricerca RAG, reranking e analisi del testo. Ambienti e modelli hanno uno stato visibile.',
          ],
          'lens' => [
            'title' => 'Conoscenza dai documenti',
            'body' => 'Organizza documenti, chunk, memoria e relazioni. Ispeziona le fonti e gli output che alimentano gli agenti.',
          ],
          'tracker' => [
            'title' => 'Nodi estendibili',
            'body' => 'Crea e importa Custom Node, verifica configurazione e permessi e attivali nel runtime sandbox disponibile nell’app.',
          ],
          'database' => [
            'title' => 'Controllo locale',
            'body' => 'Workspace e dati del runtime risiedono in SQLite sul dispositivo. Le connessioni esterne dipendono dai servizi che scegli di usare.',
          ],
          'ai' => [
            'title' => 'Modelli AI locali ed esterni',
            'body' => 'Configura provider, modelli e prompt nell’AI Center. Usa Ollama, LM Studio o i provider API e Login supportati.',
          ],
        ],
      ],
      'pricing' => [
        'metaTitle' => 'Piani e disponibilità — Trackers Lens',
        'metaDescription' => 'Stato di sviluppo, disponibilità e piani dell’app desktop Trackers Lens.',
        'badge' => 'In definizione',
        'title' => 'Prima il prodotto. Poi il piano giusto.',
        'subtitle' => 'L’app desktop è in sviluppo attivo. I piani commerciali e la disponibilità pubblica saranno comunicati con le release.',
        'progressLabel' => 'Condizioni in preparazione',
        'progressStatus' => 'Segui gli aggiornamenti',
        'progressBody' => 'I provider AI esterni possono prevedere costi e condizioni propri. L’uso di modelli locali dipende dai requisiti del tuo dispositivo.',
        'freeBody' => 'Workspace, Flow Map, persistenza locale e runtime dell’app. Segui le release per conoscere le condizioni di accesso.',
        'proBody' => 'Servizi connessi e collaborazione sono in evoluzione. Le funzioni cloud non sono necessarie per il runtime locale.',
        'enterpriseBody' => 'Contattaci per discutere integrazioni, distribuzione e requisiti della tua organizzazione.',
        'contact' => 'Contattaci',
      ],
      'roadmap' => [
        'metaTitle' => 'Roadmap dell’app — Trackers Lens',
        'metaDescription' => 'La direzione di Trackers Lens: runtime desktop, Python e AI, nodi estendibili e servizi connessi.',
        'badge' => 'Direzione del prodotto',
        'title' => 'Dall’app di oggi ai prossimi passi.',
        'subtitle' => 'Le capacità già implementate e le aree ancora in sviluppo. Le prossime fasi non rappresentano date di rilascio garantite.',
        'q2' => [
          'title' => 'Fondazione desktop',
          'body' => 'App Electron, TL Core, dati SQLite, workspace e Flow Map costituiscono la base attuale del prodotto.',
        ],
        'q3' => [
          'title' => 'Python e modelli AI',
          'body' => 'Pacchetti gestiti per embedding, RAG e NLP; AI Center e impostazioni per nodo. Prosegue la verifica delle integrazioni e dell’esperienza desktop.',
        ],
        'q4' => [
          'title' => 'Custom Node e pacchetti',
          'body' => 'Creazione, importazione, permessi e versioni dei nodi sono implementati. Distribuzione pubblica e marketplace restano da sviluppare.',
        ],
        'y2027' => [
          'title' => 'Servizi web e collaborazione',
          'body' => 'Sito e API sono unificati. Dashboard operativa, sincronizzazione e collaborazione sono passi successivi, distinti dal runtime locale.',
        ],
        'current' => 'Implementato',
        'active' => 'In consolidamento',
        'next' => 'Prossimi sviluppi',
      ],
      'changelog' => [
        'metaTitle' => 'Sviluppo dell’app — Trackers Lens',
        'metaDescription' => 'Stato delle capacità dell’app Trackers Lens: desktop, Flow Map, Python, modelli AI e sito unificato.',
        'badge' => 'Stato sviluppo · Settembre 2026',
        'title' => 'L’app, oggi.',
        'subtitle' => 'Una fotografia delle capacità implementate durante lo sviluppo, non un elenco di release pubbliche già scaricabili.',
        'items' => [
          'site' => [
            'title' => 'Sito, dashboard e API unificati',
            'body' => 'Un unico progetto web ospita pagine pubbliche, account e API Laravel. Il rinnovo della dashboard è una fase successiva.',
          ],
          'dashboard' => [
            'title' => 'Connessioni AI per nodo',
            'body' => 'L’AI Center distingue provider API e Login. I nodi mantengono la scelta di modello e le impostazioni supportate.',
          ],
          'runtime' => [
            'title' => 'Runtime Python e conoscenza',
            'body' => 'Installazione gestita dei pacchetti e dei modelli; embedding locali, ricerca RAG, reranking e annotazioni linguistiche.',
          ],
          'editors' => [
            'title' => 'Desktop, SQLite e Custom Node',
            'body' => 'Persistenza locale in TL Core, navigazione dell’app, ispezione dei dati e ciclo di creazione, importazione e attivazione dei nodi personalizzati.',
          ],
        ],
      ],
      'docs' => [
        'metaTitle' => 'Guida all’app — Trackers Lens',
        'metaDescription' => 'Orientati nell’app TL: Flow Map, runtime Python e Node.js, modelli AI, conoscenza, workspace e dati locali.',
        'badge' => 'Guida al prodotto',
        'title' => 'Dentro Trackers Lens App.',
        'subtitle' => 'Le aree principali dell’ambiente desktop e il loro ruolo nel tuo lavoro.',
        'runtime' => [
          'title' => 'App desktop e runtime',
          'body' => 'TL è un’app Electron con TL Core su Node.js. Il runtime coordina nodi JavaScript e capacità Python gestite. Nella pagina Runtime Python e Modelli puoi controllare requisiti, installazioni e stato dei pacchetti disponibili.',
        ],
        'workspace' => [
          'title' => 'Workspace e Flow Map',
          'body' => 'Organizza il lavoro in workspace. In Flow Map collega nodi, porte e canali; ispeziona input, output, errori e dipendenze. Le viste boxLens rendono i risultati consultabili nel workspace.',
        ],
        'boxes' => [
          'title' => 'AI, memoria e conoscenza',
          'body' => 'Configura il provider nell’AI Center e scegli le impostazioni per nodo. I percorsi Knowledge e RAG collegano documenti, ricerca, memoria e agenti. Verifica sempre fonti, provenienza e output; i pacchetti Python richiesti devono essere installati.',
        ],
        'storage' => [
          'title' => 'Dati locali e SQLite',
          'body' => 'TL Core gestisce la persistenza desktop in SQLite. L’app espone libreria, raccolte e strumenti di ispezione; l’interfaccia non accede direttamente al database. I servizi web hanno una persistenza separata.',
        ],
        'screens' => [
          'title' => 'Le aree dell’app',
          'body' => 'Library, Workspace, Flow Map, AI Center, Runtime Python e Modelli, Custom Nodes, Connections, Statistics e SQLite Explorer condividono la navigazione desktop. AI Chat può richiedere accesso esplicito agli strumenti e ai dati necessari.',
        ],
        'api' => [
          'title' => 'Sito e API web',
          'body' => 'Il sito ospita account, form e API Laravel sullo stesso dominio. La dashboard web è distinta dall’app desktop e mantiene per ora schermate dimostrative. Il login web non trasferisce automaticamente i workspace locali.',
        ],
      ],
      'privacy' => [
        'metaTitle' => 'Privacy — Trackers Lens',
        'metaDescription' => 'Dati locali nell’app desktop, connessioni ai modelli AI e dati dei servizi web Trackers Lens.',
        'badge' => 'Privacy',
        'title' => 'Dati e connessioni.',
        'subtitle' => 'Come sono separati il runtime sul dispositivo e i servizi che scegli di collegare.',
        'sections' => [
          's1' => [
            'title' => 'Dati dell’app',
            'body' => 'Workspace, asset, collegamenti e impostazioni del runtime sono persistiti localmente in SQLite, gestito da TL Core. La presenza di dati locali non esclude le richieste esterne configurate nei flussi.',
          ],
          's2' => [
            'title' => 'Modelli e provider AI',
            'body' => 'Puoi usare modelli locali o provider esterni. Prompt e contenuti necessari all’elaborazione sono inviati al provider selezionato quando esegui il flusso. L’installazione dei pacchetti gestiti può scaricare dipendenze e modelli.',
          ],
          's3' => [
            'title' => 'Account, newsletter e contatti',
            'body' => 'I servizi web trattano i dati inviati nei form, come email, credenziali di accesso e messaggi. I form newsletter e contatti sono gestiti dal backend del sito; l’autenticazione usa cookie di sessione.',
          ],
          's4' => [
            'title' => 'Controllo e ispezione',
            'body' => 'Nell’app puoi ispezionare configurazioni, connessioni e risultati. Le richieste di accesso degli agenti e l’attivazione dei Custom Node rendono espliciti dati e permessi coinvolti.',
          ],
        ],
      ],
      'terms' => [
        'metaTitle' => 'Termini — Trackers Lens',
        'metaDescription' => 'Informazioni sull’uso dell’app desktop, delle integrazioni AI e dei servizi web Trackers Lens.',
        'badge' => 'Termini',
        'title' => 'Un prodotto in sviluppo.',
        'subtitle' => 'Informazioni generali sullo stato del prodotto e sulle integrazioni configurate dall’utente.',
        'sections' => [
          's1' => [
            'title' => 'Stato del prodotto',
            'body' => 'Trackers Lens App è in sviluppo attivo. Disponibilità, funzionalità e piani possono cambiare; le note di sviluppo non costituiscono un impegno su una data di rilascio.',
          ],
          's2' => [
            'title' => 'Sorgenti e modelli',
            'body' => 'Scegli sorgenti, credenziali, modelli e automazioni adatti al tuo utilizzo. I provider esterni e i modelli possono prevedere condizioni, licenze e costi propri.',
          ],
          's3' => [
            'title' => 'Componenti e risultati',
            'body' => 'Esamina i permessi prima di attivare un Custom Node e verifica gli output dei modelli AI prima di utilizzarli nelle tue decisioni o automazioni.',
          ],
          's4' => [
            'title' => 'Servizi web',
            'body' => 'L’area web è separata dal runtime desktop. Marketplace, collaborazione e sincronizzazione sono funzionalità future; la loro presenza nella roadmap non implica disponibilità attuale.',
          ],
        ],
      ],
      'blog' => [
        'metaTitle' => 'Note sull’app — Trackers Lens',
        'metaDescription' => 'Note di prodotto su Trackers Lens App, runtime Python, modelli AI e sito unificato.',
        'badge' => 'Note di prodotto',
        'title' => 'Dentro l’evoluzione di TL.',
        'subtitle' => 'Le scelte che rendono dati, runtime e modelli parte dello stesso ambiente.',
        'items' => [
          'docs' => [
            'title' => 'Una guida per l’app desktop',
            'body' => 'Flow Map, dati locali e AI Center diventano i punti di partenza per orientarsi nel prodotto.',
          ],
          'api' => [
            'title' => 'Un sito, una base web',
            'body' => 'Pagine pubbliche, account e API condividono ora lo stesso progetto. L’app continua a gestire il runtime locale.',
          ],
          'runtime' => [
            'title' => 'Python e AI vicino ai tuoi dati',
            'body' => 'Pacchetti gestiti, modelli configurabili e nodi collegati rendono possibile comporre flussi di analisi e conoscenza ispezionabili.',
          ],
        ],
      ],
    ],
  ],
  'en' => [
    'locale' => 'en_US',
    'meta' => [
      'title' => 'Trackers Lens — Your desktop app for data, Python and AI',
      'description' => 'Connect data, nodes and AI models in one desktop app. Flow Map, JavaScript and Python runtimes, document retrieval and local SQLite storage.',
    ],
    'accessibility' => [
      'skip' => 'Skip to content',
      'language' => 'Language',
    ],
    'nav' => [
      'features' => 'Features',
      'why' => 'Why Trackers Lens',
      'marketplace' => 'Runtimes',
      'pricing' => 'Pricing',
      'docs' => 'Docs',
      'login' => 'Login',
      'download' => 'Notify Me',
    ],
    'hero' => [
      'badge' => 'Desktop app · Python · Node.js · AI models',
      'title' => 'Data, automation and AI. In your app.',
      'subtitle' => 'Trackers Lens is your local AI operating environment. Connect sources, nodes and models in Flow Map, work with Python and JavaScript, and follow every execution from your desktop.',
      'ctaPrimary' => 'Notify Me at Launch',
      'ctaSecondary' => 'Explore the workflow',
      'devLabel' => 'In active development',
      'devStatus' => 'Desktop app in development',
      'devBody' => 'The desktop runtime is in active development. Subscribe for release updates and news about download availability.',
      'devProgress' => 'Release progress',
      'trustPrivate' => 'Explicit permissions',
      'trustLocal' => 'Local data with SQLite',
      'trustOpen' => 'Your choice of models',
      'metricTrackers' => 'Active trackers',
      'metricData' => 'Processed data',
      'metricInsights' => 'AI Insights',
      'metricActions' => 'Automated actions',
      'chartActivity' => 'Realtime activity',
      'chartResources' => 'Resource usage',
      'previewLabel' => 'Example in-app workflow',
      'previewTitle' => 'From documents to a traceable answer',
      'previewNote' => 'Illustrative flow: packages and models are configured in the app.',
      'source' => 'Documents',
      'retrieval' => 'RAG retrieval',
      'agent' => 'AI agent',
      'output' => 'Answer and sources',
      'control' => 'Inspectable runs, logs and provenance',
    ],
    'value' => [
      'title' => 'One environment to build with AI and put it to work.',
      'subtitle' => 'From data to models, with tools that work together.',
      'cards' => [
        'monitor' => [
          'title' => 'Flow Map and nodes',
          'body' => 'Connect sources, processors, agents, memory and actions. See channels, dependencies and flow status in one place.',
        ],
        'ai' => [
          'title' => 'Local and external AI models',
          'body' => 'Configure providers, models and prompts in AI Center. Use Ollama, LM Studio or supported API and Login providers.',
        ],
        'automation' => [
          'title' => 'Managed Python',
          'body' => 'Install app-managed packages for embeddings, RAG retrieval, reranking and text analysis. Environments and models have visible status.',
        ],
        'visual' => [
          'title' => 'Knowledge from documents',
          'body' => 'Organize documents, chunks, memory and relationships. Inspect the sources and outputs that feed your agents.',
        ],
        'privacy' => [
          'title' => 'Local control',
          'body' => 'Workspaces and runtime data live in SQLite on your device. External connections depend on the services you choose to use.',
        ],
        'open' => [
          'title' => 'Extensible nodes',
          'body' => 'Create and import Custom Nodes, review their configuration and permissions, and activate them in the app’s available sandbox runtime.',
        ],
      ],
    ],
    'privacy' => [
      'badge' => 'Privacy First',
      'title' => 'Your data, your control.',
      'body' => 'Work starts on your device: the desktop app manages workspaces, flows and SQLite storage. For AI, choose local models or external services. Data sent to a provider depends on the connections and operations you authorize.',
      'pointCloud' => [
        'title' => 'No mandatory cloud',
        'body' => 'The local runtime does not require a TL cloud service.',
      ],
      'pointRuntime' => [
        'title' => 'Local runtime',
        'body' => 'Execution in the desktop app.',
      ],
      'pointDb' => [
        'title' => 'Local SQLite',
        'body' => 'Persistent data managed by TL Core.',
      ],
      'pointApi' => [
        'title' => 'Deliberate connections',
        'body' => 'Choose providers, sources and permissions.',
      ],
    ],
    'architecture' => [
      'title' => 'Python, Node.js and AI in one environment.',
      'site' => [
        'title' => 'Managed Python and models',
        'body' => 'Packages for embeddings, RAG and NLP. The app shows requirements and model status, and asks before installing them.',
      ],
      'plugin' => [
        'title' => 'Node.js and JavaScript',
        'body' => 'Electron and Node.js underpin the desktop app and TL Core. JavaScript nodes process data and automation through the runtime and its channels.',
      ],
      'chromium' => [
        'title' => 'AI models and agents',
        'body' => 'Keep provider connections separate from individual node settings. Choose the model, prompt and supported options for each task.',
      ],
    ],
    'boxes' => [
      'title' => 'Compose your flow. Follow every step.',
      'body' => 'Each Flow Map node has a role: acquire data, transform it, query knowledge or run an action. Channels, logs and previews show what happens. boxLens brings results into your workspaces.',
    ],
    'developers' => [
      'title' => 'Develop. Extend. Customize.',
      'body' => 'Start with the app’s nodes, configure Python packages and build reusable components. Custom Nodes declare ports, settings and permissions so you can inspect them before activation.',
      'docs' => 'Documentation',
      'api' => 'API Reference',
      'examples' => 'Examples',
      'community' => 'Community',
      'example' => 'A flow to compose in Flow Map',
    ],
    'stats' => [
      'users' => 'desktop environment',
      'trackers' => 'managed packages',
      'data' => 'local or external models',
      'uptime' => 'local storage',
    ],
    'pricing' => [
      'title' => 'An evolving app. Plans taking shape.',
      'subtitle' => 'Availability and terms will be published alongside app releases.',
      'free' => [
        'label' => 'Desktop app',
        'price' => 'In development',
        'body' => 'Flow Map, local data, runtimes and AI connections in TL App.',
      ],
      'pro' => [
        'label' => 'Pro',
        'price' => 'Soon',
        'body' => 'Additional services and collaboration are part of the product’s evolution.',
      ],
      'enterprise' => [
        'label' => 'Enterprise',
        'price' => 'Custom',
        'body' => 'Talk to us about your integration and deployment needs.',
      ],
    ],
    'cta' => [
      'title' => 'In development now. Launch coming soon.',
      'download' => 'Notify Me at Launch',
      'demo' => 'Explore the workflow',
      'note' => 'Subscribe for upcoming releases and desktop app availability.',
    ],
    'footer' => [
      'brandText' => 'The local AI operating environment for connecting data, Python, nodes and models in a desktop app.',
      'product' => 'Product',
      'features' => 'Features',
      'pricing' => 'Pricing',
      'roadmap' => 'Roadmap',
      'changelog' => 'Changelog',
      'resources' => 'Resources',
      'docs' => 'Documentation',
      'api' => 'API Reference',
      'examples' => 'Examples',
      'blog' => 'Blog',
      'company' => 'Company',
      'about' => 'About',
      'contact' => 'Contact',
      'privacy' => 'Privacy Policy',
      'terms' => 'Terms of Service',
      'newsletter' => 'Newsletter',
      'newsletterText' => 'Subscribe for news, updates and guides.',
      'emailPlaceholder' => 'Your email',
      'newsletterSubmit' => 'Subscribe',
      'copyright' => '© 2026 Trackers Lens. All rights reserved.',
    ],
    'auth' => [
      'close' => 'Close login',
      'kicker' => 'Dashboard access',
      'loginTitle' => 'Log in to Trackers Lens',
      'loginBody' => 'Sign in to the Trackers Lens web area. The desktop runtime and its local data are managed in the app.',
      'tabsLabel' => 'Auth mode',
      'loginTab' => 'Login',
      'registerTab' => 'Create account',
      'name' => 'Name',
      'email' => 'Email',
      'password' => 'Password',
      'passwordConfirmation' => 'Confirm password',
      'remember' => 'Remember me',
      'loginSubmit' => 'Login',
      'registerSubmit' => 'Create account',
      'connecting' => 'Connecting to the API...',
      'failed' => 'Login failed. Check your details and try again.',
      'success' => 'Login successful. Opening dashboard...',
      'saving' => 'Saving...',
      'newsletterSaved' => 'Email saved. We will notify you at launch.',
    ],
    'launch' => [
      'close' => 'Close launch notice',
      'kicker' => 'Launch coming soon',
      'title' => 'Leave your email',
      'body' => 'We will notify you about Trackers Lens App releases and download availability.',
      'submit' => 'Notify me at launch',
      'note' => 'Updates on the app, releases and early access.',
      'invalid' => 'Enter a valid email.',
    ],
    'contact' => [
      'close' => 'Close contact',
      'kicker' => 'Contact',
      'title' => 'Let us talk about Trackers Lens',
      'body' => 'Write for early access, partnerships, support or technical questions about the runtime.',
      'message' => 'Message',
      'submit' => 'Send message',
      'note' => 'The message is saved securely and sent to the Trackers Lens team.',
      'success' => 'Message sent. We will reply soon.',
      'invalid' => 'Fill in all required fields.',
    ],
    'pages' => [
      'about' => [
        'metaTitle' => 'About — Trackers Lens',
        'metaDescription' => 'About Trackers Lens: manifesto, principles and vision for a readable, controllable AI-powered local runtime.',
        'badge' => 'About',
        'title' => 'Daily data transformed into a controllable runtime.',
        'lead' => 'Trackers Lens comes from a simple and demanding choice: build tools that stay readable, local and honest as the project grows.',
        'note' => 'It is not only a dashboard. It is a way of working: less noise, more control, more care for detail. Every tracker, lens and workspace should shorten the distance between data, decision and real interface.',
        'manifestoBadge' => 'Manifesto',
        'manifestoTitle' => 'The manifesto behind Trackers Lens',
        'principles' => [
          'p1' => [
            'title' => 'Control',
            'body' => 'Users should see where data lives, which trackers run and what gets synchronized.',
          ],
          'p2' => [
            'title' => 'Local-first',
            'body' => 'The runtime lives in the desktop app and data persists in SQLite. External services are an explicit choice.',
          ],
          'p3' => [
            'title' => 'Composability',
            'body' => 'boxLens, boxTracker and workspaces should connect without becoming a rigid structure.',
          ],
          'p4' => [
            'title' => 'Precision',
            'body' => 'Every panel should explain what it measures, where it comes from and when it was updated.',
          ],
          'p5' => [
            'title' => 'Privacy',
            'body' => 'Permissions, API keys and automations must stay explicit and governable.',
          ],
          'p6' => [
            'title' => 'Resilience',
            'body' => 'Trackers, retries, logs and monitors should make errors and runtime states readable.',
          ],
          'p7' => [
            'title' => 'Simplicity',
            'body' => 'Add power without adding confusion: fewer layers, clearer intent.',
          ],
          'p8' => [
            'title' => 'Evolution',
            'body' => 'The app grows with Python runtimes, extensible nodes and configurable AI models.',
          ],
          'p9' => [
            'title' => 'Openness',
            'body' => 'Reusable components and packages help share work. A marketplace is a future direction.',
          ],
          'p10' => [
            'title' => 'Discipline',
            'body' => 'Daily quality: document, test, refine and make the product clearer.',
          ],
        ],
        'storyBadge' => 'Carlos Malleux',
        'story' => [
          'one' => 'Trackers Lens did not start as another generic app. It started as a need: controlling data sources, automations and interfaces without losing clarity.',
          'two' => 'Today Flow Map connects nodes and channels; TL Core manages local data; Python and AI models extend what you can build.',
          'three' => 'The goal is not to create a closed box, but to make data more usable, direct and verifiable, with AI and automations serving the user.',
          'four' => 'Trackers Lens is now a desktop app in development, with a local operating environment for data, knowledge and AI automation.',
          'footer' => 'Trackers Lens is built with this energy: patient technical work, care for detail and quality as a daily direction.',
        ],
      ],
      'features' => [
        'metaTitle' => 'App features — Trackers Lens',
        'metaDescription' => 'Explore Flow Map, managed Python, Node.js, AI models, knowledge and SQLite in the Trackers Lens desktop app.',
        'badge' => 'The TL operating environment',
        'title' => 'Build with data, nodes and models.',
        'subtitle' => 'A desktop app to compose flows, run analysis and connect AI to your sources. Python, JavaScript and models work within an inspectable environment.',
        'futureTitle' => 'A runtime you can follow.',
        'futureBody' => 'Open a workspace, connect nodes in Flow Map and inspect inputs, outputs and logs. The app shows requirements and installation for managed packages; for AI models, choose the connection and node settings.',
        'step1' => 'Compose the flow',
        'step2' => 'Configure runtimes and models',
        'step3' => 'Run and inspect',
        'cards' => [
          'plugin' => [
            'title' => 'Flow Map and nodes',
            'body' => 'Connect sources, processors, agents, memory and actions. See channels, dependencies and flow status in one place.',
          ],
          'workspace' => [
            'title' => 'Managed Python',
            'body' => 'Install app-managed packages for embeddings, RAG retrieval, reranking and text analysis. Environments and models have visible status.',
          ],
          'lens' => [
            'title' => 'Knowledge from documents',
            'body' => 'Organize documents, chunks, memory and relationships. Inspect the sources and outputs that feed your agents.',
          ],
          'tracker' => [
            'title' => 'Extensible nodes',
            'body' => 'Create and import Custom Nodes, review their configuration and permissions, and activate them in the app’s available sandbox runtime.',
          ],
          'database' => [
            'title' => 'Local control',
            'body' => 'Workspaces and runtime data live in SQLite on your device. External connections depend on the services you choose to use.',
          ],
          'ai' => [
            'title' => 'Local and external AI models',
            'body' => 'Configure providers, models and prompts in AI Center. Use Ollama, LM Studio or supported API and Login providers.',
          ],
        ],
      ],
      'pricing' => [
        'metaTitle' => 'Plans and availability — Trackers Lens',
        'metaDescription' => 'Development status, availability and plans for the Trackers Lens desktop app.',
        'badge' => 'Taking shape',
        'title' => 'The product first. Then the right plan.',
        'subtitle' => 'The desktop app is in active development. Commercial plans and public availability will be announced with releases.',
        'progressLabel' => 'Terms in preparation',
        'progressStatus' => 'Follow the updates',
        'progressBody' => 'External AI providers may have their own costs and terms. Local model usage depends on your device requirements.',
        'freeBody' => 'Workspaces, Flow Map, local storage and app runtimes. Follow releases for access details.',
        'proBody' => 'Connected services and collaboration are evolving. Cloud features are not required for the local runtime.',
        'enterpriseBody' => 'Contact us to discuss integrations, deployment and your organization’s requirements.',
        'contact' => 'Contact us',
      ],
      'roadmap' => [
        'metaTitle' => 'App roadmap — Trackers Lens',
        'metaDescription' => 'The direction of Trackers Lens: desktop runtime, Python and AI, extensible nodes and connected services.',
        'badge' => 'Product direction',
        'title' => 'From today’s app to the next steps.',
        'subtitle' => 'Implemented capabilities and areas still in development. Upcoming phases are not guaranteed release dates.',
        'q2' => [
          'title' => 'Desktop foundation',
          'body' => 'The Electron app, TL Core, SQLite data, workspaces and Flow Map form the current product foundation.',
        ],
        'q3' => [
          'title' => 'Python and AI models',
          'body' => 'Managed packages for embeddings, RAG and NLP; AI Center and per-node settings. Integration testing and desktop experience refinement continue.',
        ],
        'q4' => [
          'title' => 'Custom Nodes and packages',
          'body' => 'Node creation, import, permissions and versions are implemented. Public distribution and a marketplace remain to be developed.',
        ],
        'y2027' => [
          'title' => 'Web services and collaboration',
          'body' => 'The website and API are unified. An operational dashboard, synchronization and collaboration are next steps, separate from the local runtime.',
        ],
        'current' => 'Implemented',
        'active' => 'Being refined',
        'next' => 'Next developments',
      ],
      'changelog' => [
        'metaTitle' => 'App development — Trackers Lens',
        'metaDescription' => 'Trackers Lens app capabilities: desktop, Flow Map, Python, AI models and a unified website.',
        'badge' => 'Development status · September 2026',
        'title' => 'The app, today.',
        'subtitle' => 'A snapshot of capabilities implemented during development, not a list of downloadable public releases.',
        'items' => [
          'site' => [
            'title' => 'Unified website, dashboard and API',
            'body' => 'One web project hosts public pages, accounts and Laravel APIs. The dashboard refresh is a subsequent phase.',
          ],
          'dashboard' => [
            'title' => 'Per-node AI connections',
            'body' => 'AI Center distinguishes API and Login providers. Nodes retain their model choices and supported settings.',
          ],
          'runtime' => [
            'title' => 'Python runtime and knowledge',
            'body' => 'Managed package and model installation; local embeddings, RAG retrieval, reranking and linguistic annotations.',
          ],
          'editors' => [
            'title' => 'Desktop, SQLite and Custom Nodes',
            'body' => 'Local persistence in TL Core, app navigation, data inspection and the creation, import and activation lifecycle for custom nodes.',
          ],
        ],
      ],
      'docs' => [
        'metaTitle' => 'App guide — Trackers Lens',
        'metaDescription' => 'Find your way around TL App: Flow Map, Python and Node.js runtimes, AI models, knowledge, workspaces and local data.',
        'badge' => 'Product guide',
        'title' => 'Inside Trackers Lens App.',
        'subtitle' => 'The main areas of the desktop environment and their role in your work.',
        'runtime' => [
          'title' => 'Desktop app and runtimes',
          'body' => 'TL is an Electron app with TL Core on Node.js. Its runtime coordinates JavaScript nodes and managed Python capabilities. The Python Runtime and Models page shows requirements, installations and the status of available packages.',
        ],
        'workspace' => [
          'title' => 'Workspaces and Flow Map',
          'body' => 'Organize work in workspaces. In Flow Map, connect nodes, ports and channels; inspect inputs, outputs, errors and dependencies. boxLens views make results accessible in your workspace.',
        ],
        'boxes' => [
          'title' => 'AI, memory and knowledge',
          'body' => 'Configure the provider in AI Center and choose per-node settings. Knowledge and RAG workflows connect documents, retrieval, memory and agents. Inspect sources, provenance and outputs; required Python packages must be installed.',
        ],
        'storage' => [
          'title' => 'Local data and SQLite',
          'body' => 'TL Core manages desktop persistence in SQLite. The app provides a library, collections and inspection tools; the interface does not access the database directly. Web services use separate persistence.',
        ],
        'screens' => [
          'title' => 'App areas',
          'body' => 'Library, Workspace, Flow Map, AI Center, Python Runtime and Models, Custom Nodes, Connections, Statistics and SQLite Explorer share desktop navigation. AI Chat can request explicit access to the tools and data it needs.',
        ],
        'api' => [
          'title' => 'Website and web API',
          'body' => 'The website hosts accounts, forms and Laravel APIs on one domain. The web dashboard is separate from the desktop app and currently retains demonstration screens. Web login does not automatically transfer local workspaces.',
        ],
      ],
      'privacy' => [
        'metaTitle' => 'Privacy — Trackers Lens',
        'metaDescription' => 'Local data in the desktop app, AI model connections and Trackers Lens web service data.',
        'badge' => 'Privacy',
        'title' => 'Data and connections.',
        'subtitle' => 'How the on-device runtime and the services you choose to connect are separated.',
        'sections' => [
          's1' => [
            'title' => 'App data',
            'body' => 'Workspaces, assets, connections and runtime settings persist locally in SQLite, managed by TL Core. Local storage does not prevent external requests configured in your flows.',
          ],
          's2' => [
            'title' => 'AI models and providers',
            'body' => 'You can use local models or external providers. Prompts and content needed for processing are sent to the selected provider when you run the flow. Managed package installation may download dependencies and models.',
          ],
          's3' => [
            'title' => 'Accounts, newsletter and contact',
            'body' => 'Web services process submitted form data such as email, login credentials and messages. Newsletter and contact forms are handled by the website backend; authentication uses session cookies.',
          ],
          's4' => [
            'title' => 'Control and inspection',
            'body' => 'In the app you can inspect configurations, connections and results. Agent access requests and Custom Node activation make the data and permissions involved explicit.',
          ],
        ],
      ],
      'terms' => [
        'metaTitle' => 'Terms — Trackers Lens',
        'metaDescription' => 'Information about using the desktop app, AI integrations and Trackers Lens web services.',
        'badge' => 'Terms',
        'title' => 'A product in development.',
        'subtitle' => 'General information about product status and user-configured integrations.',
        'sections' => [
          's1' => [
            'title' => 'Product status',
            'body' => 'Trackers Lens App is in active development. Availability, features and plans may change; development notes are not a commitment to a release date.',
          ],
          's2' => [
            'title' => 'Sources and models',
            'body' => 'Choose sources, credentials, models and automation appropriate for your use. External providers and models may have their own terms, licenses and costs.',
          ],
          's3' => [
            'title' => 'Components and results',
            'body' => 'Review permissions before activating a Custom Node and verify AI model outputs before using them in decisions or automation.',
          ],
          's4' => [
            'title' => 'Web services',
            'body' => 'The web area is separate from the desktop runtime. Marketplace, collaboration and synchronization are future features; roadmap inclusion does not imply current availability.',
          ],
        ],
      ],
      'blog' => [
        'metaTitle' => 'App notes — Trackers Lens',
        'metaDescription' => 'Product notes on Trackers Lens App, Python runtimes, AI models and the unified website.',
        'badge' => 'Product notes',
        'title' => 'Inside TL’s evolution.',
        'subtitle' => 'The choices that bring data, runtimes and models into one environment.',
        'items' => [
          'docs' => [
            'title' => 'A guide to the desktop app',
            'body' => 'Flow Map, local data and AI Center are the starting points for finding your way around the product.',
          ],
          'api' => [
            'title' => 'One website, one web foundation',
            'body' => 'Public pages, accounts and APIs now share one project. The app continues to manage the local runtime.',
          ],
          'runtime' => [
            'title' => 'Python and AI close to your data',
            'body' => 'Managed packages, configurable models and connected nodes let you compose inspectable analysis and knowledge workflows.',
          ],
        ],
      ],
    ],
  ],
  'es' => [
    'locale' => 'es_ES',
    'meta' => [
      'title' => 'Trackers Lens — Tu app de escritorio para datos, Python e IA',
      'description' => 'Conecta datos, nodos y modelos de IA en una app de escritorio. Flow Map, runtimes JavaScript y Python, búsqueda documental y almacenamiento SQLite local.',
    ],
    'accessibility' => [
      'skip' => 'Saltar al contenido',
      'language' => 'Idioma',
    ],
    'nav' => [
      'features' => 'Funcionalidades',
      'why' => 'Por que Trackers Lens',
      'marketplace' => 'Runtimes',
      'pricing' => 'Precios',
      'docs' => 'Documentacion',
      'login' => 'Acceder',
      'download' => 'Avisarme',
    ],
    'hero' => [
      'badge' => 'App de escritorio · Python · Node.js · Modelos de IA',
      'title' => 'Datos, automatización e IA. En tu app.',
      'subtitle' => 'Trackers Lens es tu entorno operativo de IA local. Conecta fuentes, nodos y modelos en Flow Map, trabaja con Python y JavaScript y sigue cada ejecución desde tu escritorio.',
      'ctaPrimary' => 'Avisarme del Lanzamiento',
      'ctaSecondary' => 'Explora el flujo',
      'devLabel' => 'En desarrollo activo',
      'devStatus' => 'App de escritorio en desarrollo',
      'devBody' => 'El runtime de escritorio está en desarrollo activo. Suscríbete para recibir novedades sobre versiones y disponibilidad de descarga.',
      'devProgress' => 'Progreso release',
      'trustPrivate' => 'Permisos explícitos',
      'trustLocal' => 'Datos locales con SQLite',
      'trustOpen' => 'Tú eliges los modelos',
      'metricTrackers' => 'Trackers activos',
      'metricData' => 'Datos procesados',
      'metricInsights' => 'AI Insights',
      'metricActions' => 'Acciones automaticas',
      'chartActivity' => 'Actividad realtime',
      'chartResources' => 'Uso de recursos',
      'previewLabel' => 'Ejemplo de flujo en la app',
      'previewTitle' => 'De documentos a una respuesta verificable',
      'previewNote' => 'Esquema ilustrativo: los paquetes y modelos se configuran en la app.',
      'source' => 'Documentos',
      'retrieval' => 'Búsqueda RAG',
      'agent' => 'Agente de IA',
      'output' => 'Respuesta y fuentes',
      'control' => 'Ejecuciones, registros y procedencia inspeccionables',
    ],
    'value' => [
      'title' => 'Un entorno para construir con IA y ponerla a trabajar.',
      'subtitle' => 'Del dato al modelo, con herramientas que trabajan juntas.',
      'cards' => [
        'monitor' => [
          'title' => 'Flow Map y nodos',
          'body' => 'Conecta fuentes, procesadores, agentes, memoria y acciones. Consulta canales, dependencias y estado del flujo en un solo lugar.',
        ],
        'ai' => [
          'title' => 'Modelos de IA locales y externos',
          'body' => 'Configura proveedores, modelos y prompts en AI Center. Usa Ollama, LM Studio o proveedores API y Login compatibles.',
        ],
        'automation' => [
          'title' => 'Python gestionado',
          'body' => 'Instala paquetes gestionados por la app para embeddings, búsqueda RAG, reranking y análisis de texto. Entornos y modelos muestran su estado.',
        ],
        'visual' => [
          'title' => 'Conocimiento a partir de documentos',
          'body' => 'Organiza documentos, fragmentos, memoria y relaciones. Inspecciona las fuentes y salidas que utilizan tus agentes.',
        ],
        'privacy' => [
          'title' => 'Control local',
          'body' => 'Los espacios de trabajo y datos del runtime se guardan en SQLite en tu dispositivo. Las conexiones externas dependen de los servicios que elijas.',
        ],
        'open' => [
          'title' => 'Nodos extensibles',
          'body' => 'Crea e importa Custom Nodes, revisa su configuración y permisos y actívalos en el runtime aislado disponible en la app.',
        ],
      ],
    ],
    'privacy' => [
      'badge' => 'Privacy First',
      'title' => 'Tus datos, tu control.',
      'body' => 'El trabajo empieza en tu dispositivo: la app gestiona espacios de trabajo, flujos y almacenamiento SQLite. Para la IA, elige modelos locales o servicios externos. Los datos enviados a un proveedor dependen de las conexiones y operaciones que autorices.',
      'pointCloud' => [
        'title' => 'Sin cloud obligatorio',
        'body' => 'El runtime local no requiere un servicio cloud de TL.',
      ],
      'pointRuntime' => [
        'title' => 'Runtime local',
        'body' => 'Ejecución en la app de escritorio.',
      ],
      'pointDb' => [
        'title' => 'SQLite local',
        'body' => 'Datos persistentes gestionados por TL Core.',
      ],
      'pointApi' => [
        'title' => 'Conexiones conscientes',
        'body' => 'Elige proveedores, fuentes y permisos.',
      ],
    ],
    'architecture' => [
      'title' => 'Python, Node.js e IA en un mismo entorno.',
      'site' => [
        'title' => 'Python y modelos gestionados',
        'body' => 'Paquetes para embeddings, RAG y NLP. La app muestra requisitos y estado de los modelos y pide confirmación antes de instalarlos.',
      ],
      'plugin' => [
        'title' => 'Node.js y JavaScript',
        'body' => 'Electron y Node.js sostienen la app de escritorio y TL Core. Los nodos JavaScript procesan datos y automatizaciones mediante el runtime y sus canales.',
      ],
      'chromium' => [
        'title' => 'Modelos y agentes de IA',
        'body' => 'Separa la conexión al proveedor de la configuración de cada nodo. Elige modelo, prompt y opciones compatibles para cada tarea.',
      ],
    ],
    'boxes' => [
      'title' => 'Compón tu flujo. Sigue cada paso.',
      'body' => 'Cada nodo de Flow Map tiene una función: obtener datos, transformarlos, consultar conocimiento o ejecutar una acción. Canales, registros y vistas previas muestran lo que ocurre. boxLens lleva los resultados a tus espacios de trabajo.',
    ],
    'developers' => [
      'title' => 'Desarrolla. Extiende. Personaliza.',
      'body' => 'Empieza con los nodos de la app, configura paquetes Python y crea componentes reutilizables. Los Custom Nodes declaran puertos, ajustes y permisos para revisarlos antes de activarlos.',
      'docs' => 'Documentacion',
      'api' => 'API Reference',
      'examples' => 'Ejemplos',
      'community' => 'Community',
      'example' => 'Un flujo para componer en Flow Map',
    ],
    'stats' => [
      'users' => 'entorno de escritorio',
      'trackers' => 'paquetes gestionados',
      'data' => 'modelos locales o externos',
      'uptime' => 'almacenamiento local',
    ],
    'pricing' => [
      'title' => 'Una app en evolución. Planes en definición.',
      'subtitle' => 'La disponibilidad y las condiciones se publicarán junto con las versiones de la app.',
      'free' => [
        'label' => 'App de escritorio',
        'price' => 'En desarrollo',
        'body' => 'Flow Map, datos locales, runtimes y conexiones de IA en TL App.',
      ],
      'pro' => [
        'label' => 'Pro',
        'price' => 'Pronto',
        'body' => 'Los servicios adicionales y la colaboración forman parte de la evolución del producto.',
      ],
      'enterprise' => [
        'label' => 'Enterprise',
        'price' => 'Custom',
        'body' => 'Hablemos de tus necesidades de integración y distribución.',
      ],
    ],
    'cta' => [
      'title' => 'En desarrollo ahora. Lanzamiento pronto.',
      'download' => 'Avisarme del Lanzamiento',
      'demo' => 'Explora el flujo',
      'note' => 'Suscríbete para conocer las próximas versiones y la disponibilidad de la app.',
    ],
    'footer' => [
      'brandText' => 'El entorno operativo de IA local para conectar datos, Python, nodos y modelos en una app de escritorio.',
      'product' => 'Producto',
      'features' => 'Funcionalidades',
      'pricing' => 'Pricing',
      'roadmap' => 'Roadmap',
      'changelog' => 'Changelog',
      'resources' => 'Recursos',
      'docs' => 'Documentacion',
      'api' => 'API Reference',
      'examples' => 'Ejemplos',
      'blog' => 'Blog',
      'company' => 'Empresa',
      'about' => 'Quienes somos',
      'contact' => 'Contacto',
      'privacy' => 'Privacy Policy',
      'terms' => 'Terminos de servicio',
      'newsletter' => 'Newsletter',
      'newsletterText' => 'Suscribete para novedades, actualizaciones y guias.',
      'emailPlaceholder' => 'Tu email',
      'newsletterSubmit' => 'Suscribirse',
      'copyright' => '© 2026 Trackers Lens. Todos los derechos reservados.',
    ],
    'auth' => [
      'close' => 'Cerrar login',
      'kicker' => 'Acceso dashboard',
      'loginTitle' => 'Accede a Trackers Lens',
      'loginBody' => 'Accede al área web de Trackers Lens. La app gestiona el runtime de escritorio y sus datos locales.',
      'tabsLabel' => 'Modo de acceso',
      'loginTab' => 'Login',
      'registerTab' => 'Crear cuenta',
      'name' => 'Nombre',
      'email' => 'Email',
      'password' => 'Password',
      'passwordConfirmation' => 'Confirmar password',
      'remember' => 'Recordarme',
      'loginSubmit' => 'Acceder',
      'registerSubmit' => 'Crear cuenta',
      'connecting' => 'Conectando con la API...',
      'failed' => 'Acceso fallido. Revisa los datos e intentalo de nuevo.',
      'success' => 'Acceso correcto. Abriendo dashboard...',
      'saving' => 'Guardando...',
      'newsletterSaved' => 'Email guardado. Te avisaremos en el lanzamiento.',
    ],
    'launch' => [
      'close' => 'Cerrar aviso de lanzamiento',
      'kicker' => 'Lanzamiento pronto',
      'title' => 'Deja tu email',
      'body' => 'Te avisaremos de las versiones de Trackers Lens App y de la disponibilidad de descarga.',
      'submit' => 'Avisarme del lanzamiento',
      'note' => 'Novedades sobre la app, versiones y acceso anticipado.',
      'invalid' => 'Introduce un email valido.',
    ],
    'contact' => [
      'close' => 'Cerrar contacto',
      'kicker' => 'Contacto',
      'title' => 'Hablemos de Trackers Lens',
      'body' => 'Escribenos para acceso anticipado, partnerships, soporte o preguntas tecnicas sobre el runtime.',
      'message' => 'Mensaje',
      'submit' => 'Enviar mensaje',
      'note' => 'El mensaje se guarda de forma segura y se envia al equipo Trackers Lens.',
      'success' => 'Mensaje enviado. Te responderemos pronto.',
      'invalid' => 'Completa todos los campos requeridos.',
    ],
    'pages' => [
      'about' => [
        'metaTitle' => 'Quienes somos — Trackers Lens',
        'metaDescription' => 'Quienes somos Trackers Lens: manifiesto, principios y vision para un runtime local con IA, legible y controlable.',
        'badge' => 'Quienes somos',
        'title' => 'Datos diarios transformados en un runtime controlable.',
        'lead' => 'Trackers Lens nace de una decision simple y exigente: construir herramientas que sigan siendo legibles, locales y honestas mientras el proyecto crece.',
        'note' => 'No es solo un dashboard. Es una forma de trabajar: menos ruido, mas control, mas cuidado por el detalle. Cada tracker, lens y workspace debe reducir la distancia entre dato, decision e interfaz real.',
        'manifestoBadge' => 'Manifiesto',
        'manifestoTitle' => 'El manifiesto detras de Trackers Lens',
        'principles' => [
          'p1' => [
            'title' => 'Control',
            'body' => 'El usuario debe ver donde viven los datos, que trackers se ejecutan y que se sincroniza.',
          ],
          'p2' => [
            'title' => 'Local-first',
            'body' => 'El runtime vive en la app de escritorio y los datos persisten en SQLite. Los servicios externos son una elección explícita.',
          ],
          'p3' => [
            'title' => 'Composicion',
            'body' => 'boxLens, boxTracker y workspaces deben unirse sin convertirse en una estructura rigida.',
          ],
          'p4' => [
            'title' => 'Precision',
            'body' => 'Cada panel debe explicar que mide, de donde viene y cuando fue actualizado.',
          ],
          'p5' => [
            'title' => 'Privacidad',
            'body' => 'Permisos, API keys y automatizaciones deben seguir siendo explicitos y gobernables.',
          ],
          'p6' => [
            'title' => 'Resiliencia',
            'body' => 'Trackers, reintentos, logs y monitores deben hacer legibles los errores y estados del runtime.',
          ],
          'p7' => [
            'title' => 'Simplicidad',
            'body' => 'Agregar potencia sin agregar confusion: menos capas, mas intencion.',
          ],
          'p8' => [
            'title' => 'Evolucion',
            'body' => 'La app crece con runtimes Python, nodos extensibles y modelos de IA configurables.',
          ],
          'p9' => [
            'title' => 'Apertura',
            'body' => 'Los componentes y paquetes reutilizables ayudan a compartir el trabajo. El marketplace es una dirección futura.',
          ],
          'p10' => [
            'title' => 'Disciplina',
            'body' => 'Calidad diaria: documentar, probar, pulir y hacer el producto mas claro.',
          ],
        ],
        'storyBadge' => 'Carlos Malleux',
        'story' => [
          'one' => 'Trackers Lens no empezo como otra app generica. Empezo como una necesidad: controlar fuentes de datos, automatizaciones e interfaces sin perder claridad.',
          'two' => 'Hoy Flow Map conecta nodos y canales; TL Core gestiona los datos locales; Python y los modelos de IA amplían lo que puedes construir.',
          'three' => 'El objetivo no es crear una caja cerrada, sino hacer los datos mas usables, directos y verificables, con IA y automatizaciones al servicio del usuario.',
          'four' => 'Trackers Lens es hoy una app de escritorio en desarrollo, con un entorno operativo local para datos, conocimiento y automatización con IA.',
          'footer' => 'Trackers Lens se construye con esta energia: trabajo tecnico paciente, cuidado por el detalle y calidad como direccion diaria.',
        ],
      ],
      'features' => [
        'metaTitle' => 'Funciones de la app — Trackers Lens',
        'metaDescription' => 'Explora Flow Map, Python gestionado, Node.js, modelos de IA, conocimiento y SQLite en la app Trackers Lens.',
        'badge' => 'El entorno operativo TL',
        'title' => 'Construye con datos, nodos y modelos.',
        'subtitle' => 'Una app de escritorio para componer flujos, ejecutar análisis y conectar la IA con tus fuentes. Python, JavaScript y modelos trabajan en un entorno inspeccionable.',
        'futureTitle' => 'Un runtime que puedes seguir.',
        'futureBody' => 'Abre un espacio de trabajo, conecta nodos en Flow Map e inspecciona entradas, salidas y registros. La app muestra requisitos e instalación de los paquetes gestionados; para los modelos de IA, elige conexión y ajustes del nodo.',
        'step1' => 'Compón el flujo',
        'step2' => 'Configura runtimes y modelos',
        'step3' => 'Ejecuta e inspecciona',
        'cards' => [
          'plugin' => [
            'title' => 'Flow Map y nodos',
            'body' => 'Conecta fuentes, procesadores, agentes, memoria y acciones. Consulta canales, dependencias y estado del flujo en un solo lugar.',
          ],
          'workspace' => [
            'title' => 'Python gestionado',
            'body' => 'Instala paquetes gestionados por la app para embeddings, búsqueda RAG, reranking y análisis de texto. Entornos y modelos muestran su estado.',
          ],
          'lens' => [
            'title' => 'Conocimiento a partir de documentos',
            'body' => 'Organiza documentos, fragmentos, memoria y relaciones. Inspecciona las fuentes y salidas que utilizan tus agentes.',
          ],
          'tracker' => [
            'title' => 'Nodos extensibles',
            'body' => 'Crea e importa Custom Nodes, revisa su configuración y permisos y actívalos en el runtime aislado disponible en la app.',
          ],
          'database' => [
            'title' => 'Control local',
            'body' => 'Los espacios de trabajo y datos del runtime se guardan en SQLite en tu dispositivo. Las conexiones externas dependen de los servicios que elijas.',
          ],
          'ai' => [
            'title' => 'Modelos de IA locales y externos',
            'body' => 'Configura proveedores, modelos y prompts en AI Center. Usa Ollama, LM Studio o proveedores API y Login compatibles.',
          ],
        ],
      ],
      'pricing' => [
        'metaTitle' => 'Planes y disponibilidad — Trackers Lens',
        'metaDescription' => 'Estado de desarrollo, disponibilidad y planes de la app de escritorio Trackers Lens.',
        'badge' => 'En definición',
        'title' => 'Primero el producto. Después el plan adecuado.',
        'subtitle' => 'La app está en desarrollo activo. Los planes comerciales y la disponibilidad pública se comunicarán con las versiones.',
        'progressLabel' => 'Condiciones en preparación',
        'progressStatus' => 'Sigue las novedades',
        'progressBody' => 'Los proveedores de IA externos pueden tener costes y condiciones propios. El uso de modelos locales depende de los requisitos de tu dispositivo.',
        'freeBody' => 'Espacios de trabajo, Flow Map, almacenamiento local y runtimes de la app. Sigue las versiones para conocer las condiciones de acceso.',
        'proBody' => 'Los servicios conectados y la colaboración están evolucionando. Las funciones cloud no son necesarias para el runtime local.',
        'enterpriseBody' => 'Contáctanos para hablar de integraciones, distribución y requisitos de tu organización.',
        'contact' => 'Contáctanos',
      ],
      'roadmap' => [
        'metaTitle' => 'Hoja de ruta de la app — Trackers Lens',
        'metaDescription' => 'La dirección de Trackers Lens: runtime de escritorio, Python e IA, nodos extensibles y servicios conectados.',
        'badge' => 'Dirección del producto',
        'title' => 'De la app actual a los próximos pasos.',
        'subtitle' => 'Capacidades implementadas y áreas en desarrollo. Las próximas fases no representan fechas de lanzamiento garantizadas.',
        'q2' => [
          'title' => 'Base de escritorio',
          'body' => 'La app Electron, TL Core, datos SQLite, espacios de trabajo y Flow Map forman la base actual del producto.',
        ],
        'q3' => [
          'title' => 'Python y modelos de IA',
          'body' => 'Paquetes gestionados para embeddings, RAG y NLP; AI Center y ajustes por nodo. Continúan las pruebas de integración y las mejoras de la experiencia de escritorio.',
        ],
        'q4' => [
          'title' => 'Custom Nodes y paquetes',
          'body' => 'La creación, importación, permisos y versiones de nodos están implementados. La distribución pública y el marketplace siguen pendientes.',
        ],
        'y2027' => [
          'title' => 'Servicios web y colaboración',
          'body' => 'El sitio y la API están unificados. Un panel operativo, sincronización y colaboración son los siguientes pasos, separados del runtime local.',
        ],
        'current' => 'Implementado',
        'active' => 'En consolidación',
        'next' => 'Próximos desarrollos',
      ],
      'changelog' => [
        'metaTitle' => 'Desarrollo de la app — Trackers Lens',
        'metaDescription' => 'Capacidades de Trackers Lens: escritorio, Flow Map, Python, modelos de IA y sitio unificado.',
        'badge' => 'Estado de desarrollo · Septiembre de 2026',
        'title' => 'La app, hoy.',
        'subtitle' => 'Un resumen de las capacidades implementadas durante el desarrollo, no una lista de versiones públicas descargables.',
        'items' => [
          'site' => [
            'title' => 'Sitio, panel y API unificados',
            'body' => 'Un proyecto web aloja páginas públicas, cuentas y API Laravel. La renovación del panel es una fase posterior.',
          ],
          'dashboard' => [
            'title' => 'Conexiones de IA por nodo',
            'body' => 'AI Center distingue proveedores API y Login. Los nodos conservan su elección de modelo y ajustes compatibles.',
          ],
          'runtime' => [
            'title' => 'Runtime Python y conocimiento',
            'body' => 'Instalación gestionada de paquetes y modelos; embeddings locales, búsqueda RAG, reranking y anotaciones lingüísticas.',
          ],
          'editors' => [
            'title' => 'Escritorio, SQLite y Custom Nodes',
            'body' => 'Persistencia local en TL Core, navegación, inspección de datos y ciclo de creación, importación y activación de nodos personalizados.',
          ],
        ],
      ],
      'docs' => [
        'metaTitle' => 'Guía de la app — Trackers Lens',
        'metaDescription' => 'Descubre TL App: Flow Map, runtimes Python y Node.js, modelos de IA, conocimiento, espacios de trabajo y datos locales.',
        'badge' => 'Guía del producto',
        'title' => 'Dentro de Trackers Lens App.',
        'subtitle' => 'Las áreas principales del entorno de escritorio y su función en tu trabajo.',
        'runtime' => [
          'title' => 'App de escritorio y runtimes',
          'body' => 'TL es una app Electron con TL Core sobre Node.js. Su runtime coordina nodos JavaScript y capacidades Python gestionadas. La página Runtime Python y Modelos muestra requisitos, instalaciones y estado de los paquetes disponibles.',
        ],
        'workspace' => [
          'title' => 'Espacios de trabajo y Flow Map',
          'body' => 'Organiza el trabajo en espacios de trabajo. En Flow Map conecta nodos, puertos y canales; inspecciona entradas, salidas, errores y dependencias. Las vistas boxLens permiten consultar los resultados.',
        ],
        'boxes' => [
          'title' => 'IA, memoria y conocimiento',
          'body' => 'Configura el proveedor en AI Center y elige ajustes por nodo. Los flujos Knowledge y RAG conectan documentos, búsqueda, memoria y agentes. Revisa fuentes, procedencia y salidas; los paquetes Python requeridos deben estar instalados.',
        ],
        'storage' => [
          'title' => 'Datos locales y SQLite',
          'body' => 'TL Core gestiona la persistencia de escritorio en SQLite. La app ofrece biblioteca, colecciones y herramientas de inspección; la interfaz no accede directamente a la base de datos. Los servicios web tienen persistencia separada.',
        ],
        'screens' => [
          'title' => 'Áreas de la app',
          'body' => 'Library, Workspace, Flow Map, AI Center, Runtime Python y Modelos, Custom Nodes, Connections, Statistics y SQLite Explorer comparten navegación. AI Chat puede solicitar acceso explícito a las herramientas y datos que necesita.',
        ],
        'api' => [
          'title' => 'Sitio y API web',
          'body' => 'El sitio aloja cuentas, formularios y API Laravel en un mismo dominio. El panel web es distinto de la app y mantiene pantallas demostrativas. Iniciar sesión en la web no transfiere automáticamente los espacios de trabajo locales.',
        ],
      ],
      'privacy' => [
        'metaTitle' => 'Privacidad — Trackers Lens',
        'metaDescription' => 'Datos locales en la app, conexiones a modelos de IA y datos de los servicios web Trackers Lens.',
        'badge' => 'Privacidad',
        'title' => 'Datos y conexiones.',
        'subtitle' => 'Cómo se separan el runtime en tu dispositivo y los servicios que eliges conectar.',
        'sections' => [
          's1' => [
            'title' => 'Datos de la app',
            'body' => 'Espacios de trabajo, recursos, conexiones y ajustes persisten localmente en SQLite, gestionado por TL Core. El almacenamiento local no impide las solicitudes externas configuradas en los flujos.',
          ],
          's2' => [
            'title' => 'Modelos y proveedores de IA',
            'body' => 'Puedes usar modelos locales o proveedores externos. Los prompts y contenidos necesarios se envían al proveedor seleccionado al ejecutar el flujo. La instalación de paquetes puede descargar dependencias y modelos.',
          ],
          's3' => [
            'title' => 'Cuentas, boletín y contacto',
            'body' => 'Los servicios web procesan los datos enviados, como email, credenciales y mensajes. El backend gestiona los formularios de boletín y contacto; la autenticación utiliza cookies de sesión.',
          ],
          's4' => [
            'title' => 'Control e inspección',
            'body' => 'En la app puedes inspeccionar configuraciones, conexiones y resultados. Las solicitudes de acceso de agentes y la activación de Custom Nodes explicitan datos y permisos.',
          ],
        ],
      ],
      'terms' => [
        'metaTitle' => 'Condiciones — Trackers Lens',
        'metaDescription' => 'Información sobre el uso de la app, integraciones de IA y servicios web Trackers Lens.',
        'badge' => 'Condiciones',
        'title' => 'Un producto en desarrollo.',
        'subtitle' => 'Información general sobre el estado del producto y las integraciones configuradas por el usuario.',
        'sections' => [
          's1' => [
            'title' => 'Estado del producto',
            'body' => 'Trackers Lens App está en desarrollo activo. Disponibilidad, funciones y planes pueden cambiar; las notas no constituyen un compromiso sobre una fecha de lanzamiento.',
          ],
          's2' => [
            'title' => 'Fuentes y modelos',
            'body' => 'Elige fuentes, credenciales, modelos y automatizaciones adecuados para tu uso. Los proveedores externos y modelos pueden tener condiciones, licencias y costes propios.',
          ],
          's3' => [
            'title' => 'Componentes y resultados',
            'body' => 'Revisa los permisos antes de activar un Custom Node y verifica las salidas de los modelos antes de utilizarlas en decisiones o automatizaciones.',
          ],
          's4' => [
            'title' => 'Servicios web',
            'body' => 'El área web está separada del runtime de escritorio. Marketplace, colaboración y sincronización son funciones futuras; aparecer en la hoja de ruta no implica disponibilidad actual.',
          ],
        ],
      ],
      'blog' => [
        'metaTitle' => 'Notas sobre la app — Trackers Lens',
        'metaDescription' => 'Notas sobre Trackers Lens App, runtimes Python, modelos de IA y el sitio unificado.',
        'badge' => 'Notas del producto',
        'title' => 'Dentro de la evolución de TL.',
        'subtitle' => 'Las decisiones que reúnen datos, runtimes y modelos en un mismo entorno.',
        'items' => [
          'docs' => [
            'title' => 'Una guía de la app de escritorio',
            'body' => 'Flow Map, datos locales y AI Center son los puntos de partida para conocer el producto.',
          ],
          'api' => [
            'title' => 'Un sitio, una base web',
            'body' => 'Páginas públicas, cuentas y API comparten un proyecto. La app sigue gestionando el runtime local.',
          ],
          'runtime' => [
            'title' => 'Python e IA cerca de tus datos',
            'body' => 'Paquetes gestionados, modelos configurables y nodos conectados permiten componer flujos de análisis y conocimiento inspeccionables.',
          ],
        ],
      ],
    ],
  ],
];
